// components from https://www.unicode.org/versions/Unicode16.0.0/#Components

let shaping = `
# from https://www.unicode.org/Public/16.0.0/ucd/ArabicShaping.txt
# ArabicShaping-16.0.0.txt
# Date: 2024-07-30
# © 2024 Unicode®, Inc.
# Unicode and the Unicode Logo are registered trademarks of Unicode, Inc. in the U.S. and other countries.
# For terms of use and license, see https://www.unicode.org/terms_of_use.html
#
# This file is a normative contributory data file in the
# Unicode Character Database.
#
# This file defines the Joining_Type and Joining_Group property
# values for Arabic, Syriac, N'Ko, Mandaic, and Manichaean positional
# shaping, repeating in machine readable form the information
# exemplified in various tables of The Unicode Standard core specification.
#
# This file also defines Joining_Type values for
# Mongolian, Phags-pa, Psalter Pahlavi, Sogdian, Old Uyghur, Chorasmian, 
# and Adlam positional shaping,
# and Joining_Type and Joining_Group values for Hanifi Rohingya positional shaping,
# which are not listed in tables in the core specification.
#
# Script          Section  Table(s)
#
# Arabic           9.2      9-3, 9-4, 9-5, 9-7, 9-8, 9-9, 9-10, 9-11
# Syriac           9.3      9-15, 9-16, 9-17, 9-18, 9-19
# Mandaic          9.5      9-21, 9-22
# Manichaean      10.5      10-4, 10-5, 10-6, 10-7
# Psalter Pahlavi 10.6      --
# Chorasmian      10.8      --
# Mongolian       13.5      --
# Phags-pa        14.4      --
# Sogdian         14.10     --
# Old Uyghur      14.11     --
# Hanifi Rohingya 16.14     --
# N'Ko            19.4      19-5
# Adlam           19.9      --
#
# Each line contains four fields, separated by a semicolon.
#
# Field 0: the code point of a character, in hexadecimal form.
#
# Field 1: gives a short schematic name for that character.
#   The schematic name is descriptive of the shape, based as
#   consistently as possible on a name for the skeleton and
#   then the diacritic marks applied to the skeleton, if any.
#   Note that this schematic name is considered a comment,
#   and does not constitute a formal property value.
#
# Field 2: defines the joining type (property name: Joining_Type)
#   R Right_Joining
#   L Left_Joining
#   D Dual_Joining
#   C Join_Causing
#   U Non_Joining
#   T Transparent
#
# See Section 9.2, Arabic for more information on these joining types.
# Note that for cursive joining scripts which are typically rendered
# top-to-bottom, rather than right-to-left, Joining_Type=L conventionally
# refers to bottom joining, and Joining_Type=R conventionally refers
# to top joining. See Section 14.4, Phags-pa for more information on the
# interpretation of joining types in vertical layout.
#
# Field 3: defines the joining group (property name: Joining_Group)
#
# The values of the joining group are based schematically on character
# names. Where a schematic character name consists of two or more parts
# separated by spaces, the formal Joining_Group property value, as specified in
# PropertyValueAliases.txt, consists of the same name parts joined by
# underscores. Hence, the entry:
#
#   0629; TEH MARBUTA; R; TEH MARBUTA
#
# corresponds to [Joining_Group = Teh_Marbuta].
#
# Note: The property value now designated [Joining_Group = Teh_Marbuta_Goal]
#   used to apply to both of the following characters
#   in earlier versions of the standard:
#
#   U+06C2 ARABIC LETTER HEH GOAL WITH HAMZA ABOVE
#   U+06C3 ARABIC LETTER TEH MARBUTA GOAL
#
#   However, it currently applies only to U+06C3, and *not* to U+06C2.
#   To avoid destabilizing existing Joining_Group property aliases, the
#   prior Joining_Group value for U+06C3 (Hamza_On_Heh_Goal) has been
#   retained as a property value alias, despite the fact that it
#   no longer applies to its namesake character, U+06C2.
#   See PropertyValueAliases.txt.
#
# When other cursive scripts are added to the Unicode Standard in the
# future, the joining group value of all its letters will default to
# jg=No_Joining_Group in this data file. Other, more specific
# joining group values will be defined only if an explicit proposal
# to define those values exactly has been approved by the UTC. This
# is the convention exemplified by the N'Ko, Mandaic, Mongolian,
# Phags-pa, Psalter Pahlavi, Sogdian, Old Uyghur, Chorasmian, and Adlam scripts.
# Only the Arabic, Manichaean, and Syriac scripts currently have
# explicit joining group values defined for all characters, including
# those which have only a single character in a particular Joining_Group
# class. Hanifi Rohingya has explicit Joining_Group values assigned only for
# the few characters which share a particular Joining_Group class, but
# assigns jg=No_Joining_Group to all the singletons.
#
# Note: Code points that are not explicitly listed in this file are
# either of Joining_Type T or U:
#
# - Those that are not explicitly listed and that are of General_Category Mn, Me, or Cf
#   are Joining_Type=T.
# - All others not explicitly listed are Joining_Type=U.
#
# For an explicit listing of all characters of Joining_Type=T, see
# the derived property file DerivedJoiningType.txt.
# For an implementation that needs to parse for the values of
# Joining_Type, it is recommended to use DerivedJoiningType.txt
# instead of ArabicShaping.txt, to avoid the separate required step of
# calculating the set for Joining_Type=T based on General_Category values.
#
# #############################################################

# Unicode; Schematic Name; Joining Type; Joining Group

# Arabic Characters

0600; ARABIC NUMBER SIGN; U; No_Joining_Group
0601; ARABIC SIGN SANAH; U; No_Joining_Group
0602; ARABIC FOOTNOTE MARKER; U; No_Joining_Group
0603; ARABIC SIGN SAFHA; U; No_Joining_Group
0604; ARABIC SIGN SAMVAT; U; No_Joining_Group
0605; ARABIC NUMBER MARK ABOVE; U; No_Joining_Group
0608; ARABIC RAY; U; No_Joining_Group
060B; AFGHANI SIGN; U; No_Joining_Group
0620; KASHMIRI YEH; D; KASHMIRI YEH
0621; HAMZA; U; No_Joining_Group
0622; ALEF WITH MADDA ABOVE; R; ALEF
0623; ALEF WITH HAMZA ABOVE; R; ALEF
0624; WAW WITH HAMZA ABOVE; R; WAW
0625; ALEF WITH HAMZA BELOW; R; ALEF
0626; DOTLESS YEH WITH HAMZA ABOVE; D; YEH
0627; ALEF; R; ALEF
0628; BEH; D; BEH
0629; TEH MARBUTA; R; TEH MARBUTA
062A; DOTLESS BEH WITH 2 DOTS ABOVE; D; BEH
062B; DOTLESS BEH WITH 3 DOTS ABOVE; D; BEH
062C; HAH WITH DOT BELOW; D; HAH
062D; HAH; D; HAH
062E; HAH WITH DOT ABOVE; D; HAH
062F; DAL; R; DAL
0630; DAL WITH DOT ABOVE; R; DAL
0631; REH; R; REH
0632; REH WITH DOT ABOVE; R; REH
0633; SEEN; D; SEEN
0634; SEEN WITH 3 DOTS ABOVE; D; SEEN
0635; SAD; D; SAD
0636; SAD WITH DOT ABOVE; D; SAD
0637; TAH; D; TAH
0638; TAH WITH DOT ABOVE; D; TAH
0639; AIN; D; AIN
063A; AIN WITH DOT ABOVE; D; AIN
063B; KEHEH WITH 2 DOTS ABOVE; D; GAF
063C; KEHEH WITH 3 DOTS BELOW; D; GAF
063D; FARSI YEH WITH INVERTED V ABOVE; D; FARSI YEH
063E; FARSI YEH WITH 2 DOTS ABOVE; D; FARSI YEH
063F; FARSI YEH WITH 3 DOTS ABOVE; D; FARSI YEH
0640; TATWEEL; C; No_Joining_Group
0641; FEH; D; FEH
0642; QAF; D; QAF
0643; KAF; D; KAF
0644; LAM; D; LAM
0645; MEEM; D; MEEM
0646; NOON; D; NOON
0647; HEH; D; HEH
0648; WAW; R; WAW
0649; DOTLESS YEH; D; YEH
064A; YEH; D; YEH
066E; DOTLESS BEH; D; BEH
066F; DOTLESS QAF; D; QAF
0671; ALEF WITH WASLA ABOVE; R; ALEF
0672; ALEF WITH WAVY HAMZA ABOVE; R; ALEF
0673; ALEF WITH WAVY HAMZA BELOW; R; ALEF
0674; HIGH HAMZA; U; No_Joining_Group
0675; HIGH HAMZA ALEF; R; ALEF
0676; HIGH HAMZA WAW; R; WAW
0677; HIGH HAMZA WAW WITH COMMA ABOVE; R; WAW
0678; HIGH HAMZA DOTLESS YEH; D; YEH
0679; DOTLESS BEH WITH TAH ABOVE; D; BEH
067A; DOTLESS BEH WITH VERTICAL 2 DOTS ABOVE; D; BEH
067B; DOTLESS BEH WITH VERTICAL 2 DOTS BELOW; D; BEH
067C; DOTLESS BEH WITH ATTACHED RING BELOW AND 2 DOTS ABOVE; D; BEH
067D; DOTLESS BEH WITH INVERTED 3 DOTS ABOVE; D; BEH
067E; DOTLESS BEH WITH 3 DOTS BELOW; D; BEH
067F; DOTLESS BEH WITH 4 DOTS ABOVE; D; BEH
0680; DOTLESS BEH WITH 4 DOTS BELOW; D; BEH
0681; HAH WITH HAMZA ABOVE; D; HAH
0682; HAH WITH VERTICAL 2 DOTS ABOVE; D; HAH
0683; HAH WITH 2 DOTS BELOW; D; HAH
0684; HAH WITH VERTICAL 2 DOTS BELOW; D; HAH
0685; HAH WITH 3 DOTS ABOVE; D; HAH
0686; HAH WITH 3 DOTS BELOW; D; HAH
0687; HAH WITH 4 DOTS BELOW; D; HAH
0688; DAL WITH TAH ABOVE; R; DAL
0689; DAL WITH ATTACHED RING BELOW; R; DAL
068A; DAL WITH DOT BELOW; R; DAL
068B; DAL WITH DOT BELOW AND TAH ABOVE; R; DAL
068C; DAL WITH 2 DOTS ABOVE; R; DAL
068D; DAL WITH 2 DOTS BELOW; R; DAL
068E; DAL WITH 3 DOTS ABOVE; R; DAL
068F; DAL WITH INVERTED 3 DOTS ABOVE; R; DAL
0690; DAL WITH 4 DOTS ABOVE; R; DAL
0691; REH WITH TAH ABOVE; R; REH
0692; REH WITH V ABOVE; R; REH
0693; REH WITH ATTACHED RING BELOW; R; REH
0694; REH WITH DOT BELOW; R; REH
0695; REH WITH V BELOW; R; REH
0696; REH WITH DOT BELOW AND DOT WITHIN; R; REH
0697; REH WITH 2 DOTS ABOVE; R; REH
0698; REH WITH 3 DOTS ABOVE; R; REH
0699; REH WITH 4 DOTS ABOVE; R; REH
069A; SEEN WITH DOT BELOW AND DOT ABOVE; D; SEEN
069B; SEEN WITH 3 DOTS BELOW; D; SEEN
069C; SEEN WITH 3 DOTS BELOW AND 3 DOTS ABOVE; D; SEEN
069D; SAD WITH 2 DOTS BELOW; D; SAD
069E; SAD WITH 3 DOTS ABOVE; D; SAD
069F; TAH WITH 3 DOTS ABOVE; D; TAH
06A0; AIN WITH 3 DOTS ABOVE; D; AIN
06A1; DOTLESS FEH; D; FEH
06A2; DOTLESS FEH WITH DOT BELOW; D; FEH
06A3; FEH WITH DOT BELOW; D; FEH
06A4; DOTLESS FEH WITH 3 DOTS ABOVE; D; FEH
06A5; DOTLESS FEH WITH 3 DOTS BELOW; D; FEH
06A6; DOTLESS FEH WITH 4 DOTS ABOVE; D; FEH
06A7; DOTLESS QAF WITH DOT ABOVE; D; QAF
06A8; DOTLESS QAF WITH 3 DOTS ABOVE; D; QAF
06A9; KEHEH; D; GAF
06AA; SWASH KAF; D; SWASH KAF
06AB; KEHEH WITH ATTACHED RING BELOW; D; GAF
06AC; KAF WITH DOT ABOVE; D; KAF
06AD; KAF WITH 3 DOTS ABOVE; D; KAF
06AE; KAF WITH 3 DOTS BELOW; D; KAF
06AF; GAF; D; GAF
06B0; GAF WITH ATTACHED RING BELOW; D; GAF
06B1; GAF WITH 2 DOTS ABOVE; D; GAF
06B2; GAF WITH 2 DOTS BELOW; D; GAF
06B3; GAF WITH VERTICAL 2 DOTS BELOW; D; GAF
06B4; GAF WITH 3 DOTS ABOVE; D; GAF
06B5; LAM WITH V ABOVE; D; LAM
06B6; LAM WITH DOT ABOVE; D; LAM
06B7; LAM WITH 3 DOTS ABOVE; D; LAM
06B8; LAM WITH 3 DOTS BELOW; D; LAM
06B9; NOON WITH DOT BELOW; D; NOON
06BA; DOTLESS NOON; D; NOON
06BB; DOTLESS NOON WITH TAH ABOVE; D; NOON
06BC; NOON WITH ATTACHED RING BELOW; D; NOON
06BD; NYA; D; NYA
06BE; KNOTTED HEH; D; KNOTTED HEH
06BF; HAH WITH 3 DOTS BELOW AND DOT ABOVE; D; HAH
06C0; DOTLESS TEH MARBUTA WITH HAMZA ABOVE; R; TEH MARBUTA
06C1; HEH GOAL; D; HEH GOAL
06C2; HEH GOAL WITH HAMZA ABOVE; D; HEH GOAL
06C3; TEH MARBUTA GOAL; R; TEH MARBUTA GOAL
06C4; WAW WITH ATTACHED RING WITHIN; R; WAW
06C5; WAW WITH LOOP; R; WAW
06C6; WAW WITH V ABOVE; R; WAW
06C7; WAW WITH COMMA ABOVE; R; WAW
06C8; WAW WITH ALEF ABOVE; R; WAW
06C9; WAW WITH INVERTED V ABOVE; R; WAW
06CA; WAW WITH 2 DOTS ABOVE; R; WAW
06CB; WAW WITH 3 DOTS ABOVE; R; WAW
06CC; FARSI YEH; D; FARSI YEH
06CD; YEH WITH TAIL; R; YEH WITH TAIL
06CE; FARSI YEH WITH V ABOVE; D; FARSI YEH
06CF; WAW WITH DOT ABOVE; R; WAW
06D0; DOTLESS YEH WITH VERTICAL 2 DOTS BELOW; D; YEH
06D1; DOTLESS YEH WITH 3 DOTS BELOW; D; YEH
06D2; YEH BARREE; R; YEH BARREE
06D3; YEH BARREE WITH HAMZA ABOVE; R; YEH BARREE
06D5; DOTLESS TEH MARBUTA; R; TEH MARBUTA
06DD; ARABIC END OF AYAH; U; No_Joining_Group
06EE; DAL WITH INVERTED V ABOVE; R; DAL
06EF; REH WITH INVERTED V ABOVE; R; REH
06FA; SEEN WITH DOT BELOW AND 3 DOTS ABOVE; D; SEEN
06FB; SAD WITH DOT BELOW AND DOT ABOVE; D; SAD
06FC; AIN WITH DOT BELOW AND DOT ABOVE; D; AIN
06FF; KNOTTED HEH WITH INVERTED V ABOVE; D; KNOTTED HEH

# Syriac Characters

070F; SYRIAC ABBREVIATION MARK; T; No_Joining_Group
0710; ALAPH; R; ALAPH
0712; BETH; D; BETH
0713; GAMAL; D; GAMAL
0714; GAMAL GARSHUNI; D; GAMAL
0715; DALATH; R; DALATH RISH
0716; DOTLESS DALATH RISH; R; DALATH RISH
0717; HE; R; HE
0718; WAW; R; SYRIAC WAW
0719; ZAIN; R; ZAIN
071A; HETH; D; HETH
071B; TETH; D; TETH
071C; TETH GARSHUNI; D; TETH
071D; YUDH; D; YUDH
071E; YUDH HE; R; YUDH HE
071F; KAPH; D; KAPH
0720; LAMADH; D; LAMADH
0721; MIM; D; MIM
0722; NUN; D; NUN
0723; SEMKATH; D; SEMKATH
0724; FINAL SEMKATH; D; FINAL SEMKATH
0725; E; D; E
0726; PE; D; PE
0727; REVERSED PE; D; REVERSED PE
0728; SADHE; R; SADHE
0729; QAPH; D; QAPH
072A; RISH; R; DALATH RISH
072B; SHIN; D; SHIN
072C; TAW; R; TAW
072D; PERSIAN BHETH; D; BETH
072E; PERSIAN GHAMAL; D; GAMAL
072F; PERSIAN DHALATH; R; DALATH RISH
074D; SOGDIAN ZHAIN; R; ZHAIN
074E; SOGDIAN KHAPH; D; KHAPH
074F; SOGDIAN FE; D; FE

# Arabic Supplement Characters

0750; DOTLESS BEH WITH HORIZONTAL 3 DOTS BELOW; D; BEH
0751; BEH WITH 3 DOTS ABOVE; D; BEH
0752; DOTLESS BEH WITH INVERTED 3 DOTS BELOW; D; BEH
0753; DOTLESS BEH WITH INVERTED 3 DOTS BELOW AND 2 DOTS ABOVE; D; BEH
0754; DOTLESS BEH WITH 2 DOTS BELOW AND DOT ABOVE; D; BEH
0755; DOTLESS BEH WITH INVERTED V BELOW; D; BEH
0756; DOTLESS BEH WITH V ABOVE; D; BEH
0757; HAH WITH 2 DOTS ABOVE; D; HAH
0758; HAH WITH INVERTED 3 DOTS BELOW; D; HAH
0759; DAL WITH VERTICAL 2 DOTS BELOW AND TAH ABOVE; R; DAL
075A; DAL WITH INVERTED V BELOW; R; DAL
075B; REH WITH BAR; R; REH
075C; SEEN WITH 4 DOTS ABOVE; D; SEEN
075D; AIN WITH 2 DOTS ABOVE; D; AIN
075E; AIN WITH INVERTED 3 DOTS ABOVE; D; AIN
075F; AIN WITH VERTICAL 2 DOTS ABOVE; D; AIN
0760; DOTLESS FEH WITH 2 DOTS BELOW; D; FEH
0761; DOTLESS FEH WITH INVERTED 3 DOTS BELOW; D; FEH
0762; KEHEH WITH DOT ABOVE; D; GAF
0763; KEHEH WITH 3 DOTS ABOVE; D; GAF
0764; KEHEH WITH INVERTED 3 DOTS BELOW; D; GAF
0765; MEEM WITH DOT ABOVE; D; MEEM
0766; MEEM WITH DOT BELOW; D; MEEM
0767; NOON WITH 2 DOTS BELOW; D; NOON
0768; NOON WITH TAH ABOVE; D; NOON
0769; NOON WITH V ABOVE; D; NOON
076A; LAM WITH BAR; D; LAM
076B; REH WITH VERTICAL 2 DOTS ABOVE; R; REH
076C; REH WITH HAMZA ABOVE; R; REH
076D; SEEN WITH VERTICAL 2 DOTS ABOVE; D; SEEN
076E; HAH WITH TAH BELOW; D; HAH
076F; HAH WITH TAH AND 2 DOTS BELOW; D; HAH
0770; SEEN WITH 2 DOTS AND TAH ABOVE; D; SEEN
0771; REH WITH 2 DOTS AND TAH ABOVE; R; REH
0772; HAH WITH TAH ABOVE; D; HAH
0773; ALEF WITH DIGIT TWO ABOVE; R; ALEF
0774; ALEF WITH DIGIT THREE ABOVE; R; ALEF
0775; FARSI YEH WITH DIGIT TWO ABOVE; D; FARSI YEH
0776; FARSI YEH WITH DIGIT THREE ABOVE; D; FARSI YEH
0777; DOTLESS YEH WITH DIGIT FOUR BELOW; D; YEH
0778; WAW WITH DIGIT TWO ABOVE; R; WAW
0779; WAW WITH DIGIT THREE ABOVE; R; WAW
077A; BURUSHASKI YEH BARREE WITH DIGIT TWO ABOVE; D; BURUSHASKI YEH BARREE
077B; BURUSHASKI YEH BARREE WITH DIGIT THREE ABOVE; D; BURUSHASKI YEH BARREE
077C; HAH WITH DIGIT FOUR BELOW; D; HAH
077D; SEEN WITH DIGIT FOUR ABOVE; D; SEEN
077E; SEEN WITH INVERTED V ABOVE; D; SEEN
077F; KAF WITH 2 DOTS ABOVE; D; KAF

# N'Ko Characters

07CA; NKO A; D; No_Joining_Group
07CB; NKO EE; D; No_Joining_Group
07CC; NKO I; D; No_Joining_Group
07CD; NKO E; D; No_Joining_Group
07CE; NKO U; D; No_Joining_Group
07CF; NKO OO; D; No_Joining_Group
07D0; NKO O; D; No_Joining_Group
07D1; NKO DAGBASINNA; D; No_Joining_Group
07D2; NKO N; D; No_Joining_Group
07D3; NKO BA; D; No_Joining_Group
07D4; NKO PA; D; No_Joining_Group
07D5; NKO TA; D; No_Joining_Group
07D6; NKO JA; D; No_Joining_Group
07D7; NKO CHA; D; No_Joining_Group
07D8; NKO DA; D; No_Joining_Group
07D9; NKO RA; D; No_Joining_Group
07DA; NKO RRA; D; No_Joining_Group
07DB; NKO SA; D; No_Joining_Group
07DC; NKO GBA; D; No_Joining_Group
07DD; NKO FA; D; No_Joining_Group
07DE; NKO KA; D; No_Joining_Group
07DF; NKO LA; D; No_Joining_Group
07E0; NKO NA WOLOSO; D; No_Joining_Group
07E1; NKO MA; D; No_Joining_Group
07E2; NKO NYA; D; No_Joining_Group
07E3; NKO NA; D; No_Joining_Group
07E4; NKO HA; D; No_Joining_Group
07E5; NKO WA; D; No_Joining_Group
07E6; NKO YA; D; No_Joining_Group
07E7; NKO NYA WOLOSO; D; No_Joining_Group
07E8; NKO JONA JA; D; No_Joining_Group
07E9; NKO JONA CHA; D; No_Joining_Group
07EA; NKO JONA RA; D; No_Joining_Group
07FA; NKO LAJANYALAN; C; No_Joining_Group

# Mandaic Characters

0840; MANDAIC HALQA; R; No_Joining_Group
0841; MANDAIC AB; D; No_Joining_Group
0842; MANDAIC AG; D; No_Joining_Group
0843; MANDAIC AD; D; No_Joining_Group
0844; MANDAIC AH; D; No_Joining_Group
0845; MANDAIC USHENNA; D; No_Joining_Group
0846; MANDAIC AZ; R; No_Joining_Group
0847; MANDAIC IT; R; No_Joining_Group
0848; MANDAIC ATT; D; No_Joining_Group
0849; MANDAIC AKSA; R; No_Joining_Group
084A; MANDAIC AK; D; No_Joining_Group
084B; MANDAIC AL; D; No_Joining_Group
084C; MANDAIC AM; D; No_Joining_Group
084D; MANDAIC AN; D; No_Joining_Group
084E; MANDAIC AS; D; No_Joining_Group
084F; MANDAIC IN; D; No_Joining_Group
0850; MANDAIC AP; D; No_Joining_Group
0851; MANDAIC ASZ; D; No_Joining_Group
0852; MANDAIC AQ; D; No_Joining_Group
0853; MANDAIC AR; D; No_Joining_Group
0854; MANDAIC ASH; R; No_Joining_Group
0855; MANDAIC AT; D; No_Joining_Group
0856; MANDAIC DUSHENNA; R; No_Joining_Group
0857; MANDAIC KAD; R; No_Joining_Group
0858; MANDAIC AIN; R; No_Joining_Group

# Syriac Supplement Characters

0860; MALAYALAM NGA; D; MALAYALAM NGA
0861; MALAYALAM JA; U; MALAYALAM JA
0862; MALAYALAM NYA; D; MALAYALAM NYA
0863; MALAYALAM TTA; D; MALAYALAM TTA
0864; MALAYALAM NNA; D; MALAYALAM NNA
0865; MALAYALAM NNNA; D; MALAYALAM NNNA
0866; MALAYALAM BHA; U; MALAYALAM BHA
0867; MALAYALAM RA; R; MALAYALAM RA
0868; MALAYALAM LLA; D; MALAYALAM LLA
0869; MALAYALAM LLLA; R; MALAYALAM LLLA
086A; MALAYALAM SSA; R; MALAYALAM SSA

# Arabic Extended-B Characters

0870; ALEF WITH ATTACHED FATHA; R; ALEF
0871; ALEF WITH ATTACHED TOP RIGHT FATHA; R; ALEF
0872; ALEF WITH RIGHT MIDDLE STROKE; R; ALEF
0873; ALEF WITH LEFT MIDDLE STROKE; R; ALEF
0874; ALEF WITH ATTACHED KASRA; R; ALEF
0875; ALEF WITH ATTACHED BOTTOM RIGHT KASRA; R; ALEF
0876; ALEF WITH ATTACHED ROUND DOT ABOVE; R; ALEF
0877; ALEF WITH ATTACHED RIGHT ROUND DOT; R; ALEF
0878; ALEF WITH ATTACHED LEFT ROUND DOT; R; ALEF
0879; ALEF WITH ATTACHED ROUND DOT BELOW; R; ALEF
087A; ALEF WITH DOT ABOVE; R; ALEF
087B; ALEF WITH ATTACHED TOP RIGHT FATHA AND DOT ABOVE; R; ALEF
087C; ALEF WITH RIGHT MIDDLE STROKE AND DOT ABOVE; R; ALEF
087D; ALEF WITH ATTACHED BOTTOM RIGHT KASRA AND DOT ABOVE; R; ALEF
087E; ALEF WITH ATTACHED TOP RIGHT FATHA AND LEFT RING; R; ALEF
087F; ALEF WITH RIGHT MIDDLE STROKE AND LEFT RING; R; ALEF
0880; ALEF WITH ATTACHED BOTTOM RIGHT KASRA AND LEFT RING; R; ALEF
0881; ALEF WITH ATTACHED RIGHT HAMZA; R; ALEF
0882; ALEF WITH ATTACHED LEFT HAMZA; R; ALEF
0883; TATWEEL WITH OVERSTRUCK HAMZA; C; No_Joining_Group
0884; TATWEEL WITH OVERSTRUCK WAW; C; No_Joining_Group
0885; TATWEEL WITH TWO DOTS BELOW; C; No_Joining_Group
0886; THIN YEH; D; THIN YEH
0887; ARABIC BASELINE ROUND DOT; U; No_Joining_Group
0888; ARABIC RAISED ROUND DOT; U; No_Joining_Group
0889; DOTLESS NOON WITH INVERTED V ABOVE; D; NOON
088A; HAH WITH INVERTED V BELOW; D; HAH
088B; TAH WITH DOT BELOW; D; TAH
088C; TAH WITH 3 DOTS BELOW; D; TAH
088D; KEHEH WITH VERTICAL 2 DOTS BELOW; D; GAF
088E; VERTICAL TAIL; R; VERTICAL TAIL
0890; ARABIC POUND MARK ABOVE; U; No_Joining_Group
0891; ARABIC PIASTRE MARK ABOVE; U; No_Joining_Group

# Arabic Extended-A Characters

08A0; DOTLESS BEH WITH V BELOW; D; BEH
08A1; BEH WITH HAMZA ABOVE; D; BEH
08A2; HAH WITH DOT BELOW AND 2 DOTS ABOVE; D; HAH
08A3; TAH WITH 2 DOTS ABOVE; D; TAH
08A4; DOTLESS FEH WITH DOT BELOW AND 3 DOTS ABOVE; D; FEH
08A5; QAF WITH DOT BELOW; D; QAF
08A6; LAM WITH DOUBLE BAR; D; LAM
08A7; MEEM WITH 3 DOTS ABOVE; D; MEEM
08A8; YEH WITH HAMZA ABOVE; D; YEH
08A9; YEH WITH DOT ABOVE; D; YEH
08AA; REH WITH LOOP; R; REH
08AB; WAW WITH DOT WITHIN; R; WAW
08AC; ROHINGYA YEH; R; ROHINGYA YEH
08AD; LOW ALEF; U; No_Joining_Group
08AE; DAL WITH 3 DOTS BELOW; R; DAL
08AF; SAD WITH 3 DOTS BELOW; D; SAD
08B0; KEHEH WITH STROKE BELOW; D; GAF
08B1; STRAIGHT WAW; R; STRAIGHT WAW
08B2; REH WITH DOT AND INVERTED V ABOVE; R; REH
08B3; AIN WITH 3 DOTS BELOW; D; AIN
08B4; KAF WITH DOT BELOW; D; KAF
08B5; DOTLESS QAF WITH DOT BELOW; D; QAF
08B6; BEH WITH MEEM ABOVE; D; BEH
08B7; DOTLESS BEH WITH 3 DOTS BELOW AND MEEM ABOVE; D; BEH
08B8; DOTLESS BEH WITH TEH ABOVE; D; BEH
08B9; REH WITH NOON ABOVE; R; REH
08BA; YEH WITH NOON ABOVE; D; YEH
08BB; AFRICAN FEH; D; AFRICAN FEH
08BC; AFRICAN QAF; D; AFRICAN QAF
08BD; AFRICAN NOON; D; AFRICAN NOON
08BE; DOTLESS BEH WITH 3 DOTS BELOW AND V ABOVE; D; BEH
08BF; DOTLESS BEH WITH 2 DOTS AND V ABOVE; D; BEH
08C0; DOTLESS BEH WITH TAH AND V ABOVE; D; BEH
08C1; HAH WITH 3 DOTS BELOW AND V ABOVE; D; HAH
08C2; KEHEH WITH V ABOVE; D; GAF
08C3; AIN WITH DIAMOND 4 DOTS ABOVE; D; AIN
08C4; AFRICAN QAF WITH 3 DOTS ABOVE; D; AFRICAN QAF
08C5; HAH WITH DOT BELOW AND 3 DOTS ABOVE; D; HAH
08C6; HAH WITH DIAMOND 4 DOTS BELOW; D; HAH
08C7; LAM WITH TAH ABOVE; D; LAM
08C8; KEHEH WITH ELONGATED HAMZA ABOVE; D; GAF
08E2; ARABIC DISPUTED END OF AYAH; U; No_Joining_Group

# Mongolian Characters

1806; MONGOLIAN TODO SOFT HYPHEN; U; No_Joining_Group
1807; MONGOLIAN SIBE SYLLABLE BOUNDARY MARKER; D; No_Joining_Group
180A; MONGOLIAN NIRUGU; C; No_Joining_Group
180E; MONGOLIAN VOWEL SEPARATOR; U; No_Joining_Group
1820; MONGOLIAN A; D; No_Joining_Group
1821; MONGOLIAN E; D; No_Joining_Group
1822; MONGOLIAN I; D; No_Joining_Group
1823; MONGOLIAN O; D; No_Joining_Group
1824; MONGOLIAN U; D; No_Joining_Group
1825; MONGOLIAN OE; D; No_Joining_Group
1826; MONGOLIAN UE; D; No_Joining_Group
1827; MONGOLIAN EE; D; No_Joining_Group
1828; MONGOLIAN NA; D; No_Joining_Group
1829; MONGOLIAN ANG; D; No_Joining_Group
182A; MONGOLIAN BA; D; No_Joining_Group
182B; MONGOLIAN PA; D; No_Joining_Group
182C; MONGOLIAN QA; D; No_Joining_Group
182D; MONGOLIAN GA; D; No_Joining_Group
182E; MONGOLIAN MA; D; No_Joining_Group
182F; MONGOLIAN LA; D; No_Joining_Group
1830; MONGOLIAN SA; D; No_Joining_Group
1831; MONGOLIAN SHA; D; No_Joining_Group
1832; MONGOLIAN TA; D; No_Joining_Group
1833; MONGOLIAN DA; D; No_Joining_Group
1834; MONGOLIAN CHA; D; No_Joining_Group
1835; MONGOLIAN JA; D; No_Joining_Group
1836; MONGOLIAN YA; D; No_Joining_Group
1837; MONGOLIAN RA; D; No_Joining_Group
1838; MONGOLIAN WA; D; No_Joining_Group
1839; MONGOLIAN FA; D; No_Joining_Group
183A; MONGOLIAN KA; D; No_Joining_Group
183B; MONGOLIAN KHA; D; No_Joining_Group
183C; MONGOLIAN TSA; D; No_Joining_Group
183D; MONGOLIAN ZA; D; No_Joining_Group
183E; MONGOLIAN HAA; D; No_Joining_Group
183F; MONGOLIAN ZRA; D; No_Joining_Group
1840; MONGOLIAN LHA; D; No_Joining_Group
1841; MONGOLIAN ZHI; D; No_Joining_Group
1842; MONGOLIAN CHI; D; No_Joining_Group
1843; MONGOLIAN TODO LONG VOWEL SIGN; D; No_Joining_Group
1844; MONGOLIAN TODO E; D; No_Joining_Group
1845; MONGOLIAN TODO I; D; No_Joining_Group
1846; MONGOLIAN TODO O; D; No_Joining_Group
1847; MONGOLIAN TODO U; D; No_Joining_Group
1848; MONGOLIAN TODO OE; D; No_Joining_Group
1849; MONGOLIAN TODO UE; D; No_Joining_Group
184A; MONGOLIAN TODO ANG; D; No_Joining_Group
184B; MONGOLIAN TODO BA; D; No_Joining_Group
184C; MONGOLIAN TODO PA; D; No_Joining_Group
184D; MONGOLIAN TODO QA; D; No_Joining_Group
184E; MONGOLIAN TODO GA; D; No_Joining_Group
184F; MONGOLIAN TODO MA; D; No_Joining_Group
1850; MONGOLIAN TODO TA; D; No_Joining_Group
1851; MONGOLIAN TODO DA; D; No_Joining_Group
1852; MONGOLIAN TODO CHA; D; No_Joining_Group
1853; MONGOLIAN TODO JA; D; No_Joining_Group
1854; MONGOLIAN TODO TSA; D; No_Joining_Group
1855; MONGOLIAN TODO YA; D; No_Joining_Group
1856; MONGOLIAN TODO WA; D; No_Joining_Group
1857; MONGOLIAN TODO KA; D; No_Joining_Group
1858; MONGOLIAN TODO GAA; D; No_Joining_Group
1859; MONGOLIAN TODO HAA; D; No_Joining_Group
185A; MONGOLIAN TODO JIA; D; No_Joining_Group
185B; MONGOLIAN TODO NIA; D; No_Joining_Group
185C; MONGOLIAN TODO DZA; D; No_Joining_Group
185D; MONGOLIAN SIBE E; D; No_Joining_Group
185E; MONGOLIAN SIBE I; D; No_Joining_Group
185F; MONGOLIAN SIBE IY; D; No_Joining_Group
1860; MONGOLIAN SIBE UE; D; No_Joining_Group
1861; MONGOLIAN SIBE U; D; No_Joining_Group
1862; MONGOLIAN SIBE ANG; D; No_Joining_Group
1863; MONGOLIAN SIBE KA; D; No_Joining_Group
1864; MONGOLIAN SIBE GA; D; No_Joining_Group
1865; MONGOLIAN SIBE HA; D; No_Joining_Group
1866; MONGOLIAN SIBE PA; D; No_Joining_Group
1867; MONGOLIAN SIBE SHA; D; No_Joining_Group
1868; MONGOLIAN SIBE TA; D; No_Joining_Group
1869; MONGOLIAN SIBE DA; D; No_Joining_Group
186A; MONGOLIAN SIBE JA; D; No_Joining_Group
186B; MONGOLIAN SIBE FA; D; No_Joining_Group
186C; MONGOLIAN SIBE GAA; D; No_Joining_Group
186D; MONGOLIAN SIBE HAA; D; No_Joining_Group
186E; MONGOLIAN SIBE TSA; D; No_Joining_Group
186F; MONGOLIAN SIBE ZA; D; No_Joining_Group
1870; MONGOLIAN SIBE RAA; D; No_Joining_Group
1871; MONGOLIAN SIBE CHA; D; No_Joining_Group
1872; MONGOLIAN SIBE ZHA; D; No_Joining_Group
1873; MONGOLIAN MANCHU I; D; No_Joining_Group
1874; MONGOLIAN MANCHU KA; D; No_Joining_Group
1875; MONGOLIAN MANCHU RA; D; No_Joining_Group
1876; MONGOLIAN MANCHU FA; D; No_Joining_Group
1877; MONGOLIAN MANCHU ZHA; D; No_Joining_Group
1878; MONGOLIAN CHA WITH 2 DOTS; D; No_Joining_Group
1880; MONGOLIAN ALI GALI ANUSVARA ONE; U; No_Joining_Group
1881; MONGOLIAN ALI GALI VISARGA ONE; U; No_Joining_Group
1882; MONGOLIAN ALI GALI DAMARU; U; No_Joining_Group
1883; MONGOLIAN ALI GALI UBADAMA; U; No_Joining_Group
1884; MONGOLIAN ALI GALI INVERTED UBADAMA; U; No_Joining_Group
1885; MONGOLIAN ALI GALI BALUDA; T; No_Joining_Group
1886; MONGOLIAN ALI GALI THREE BALUDA; T; No_Joining_Group
1887; MONGOLIAN ALI GALI A; D; No_Joining_Group
1888; MONGOLIAN ALI GALI I; D; No_Joining_Group
1889; MONGOLIAN ALI GALI KA; D; No_Joining_Group
188A; MONGOLIAN ALI GALI NGA; D; No_Joining_Group
188B; MONGOLIAN ALI GALI CA; D; No_Joining_Group
188C; MONGOLIAN ALI GALI TTA; D; No_Joining_Group
188D; MONGOLIAN ALI GALI TTHA; D; No_Joining_Group
188E; MONGOLIAN ALI GALI DDA; D; No_Joining_Group
188F; MONGOLIAN ALI GALI NNA; D; No_Joining_Group
1890; MONGOLIAN ALI GALI TA; D; No_Joining_Group
1891; MONGOLIAN ALI GALI DA; D; No_Joining_Group
1892; MONGOLIAN ALI GALI PA; D; No_Joining_Group
1893; MONGOLIAN ALI GALI PHA; D; No_Joining_Group
1894; MONGOLIAN ALI GALI SSA; D; No_Joining_Group
1895; MONGOLIAN ALI GALI ZHA; D; No_Joining_Group
1896; MONGOLIAN ALI GALI ZA; D; No_Joining_Group
1897; MONGOLIAN ALI GALI AH; D; No_Joining_Group
1898; MONGOLIAN TODO ALI GALI TA; D; No_Joining_Group
1899; MONGOLIAN TODO ALI GALI ZHA; D; No_Joining_Group
189A; MONGOLIAN MANCHU ALI GALI GHA; D; No_Joining_Group
189B; MONGOLIAN MANCHU ALI GALI NGA; D; No_Joining_Group
189C; MONGOLIAN MANCHU ALI GALI CA; D; No_Joining_Group
189D; MONGOLIAN MANCHU ALI GALI JHA; D; No_Joining_Group
189E; MONGOLIAN MANCHU ALI GALI TTA; D; No_Joining_Group
189F; MONGOLIAN MANCHU ALI GALI DDHA; D; No_Joining_Group
18A0; MONGOLIAN MANCHU ALI GALI TA; D; No_Joining_Group
18A1; MONGOLIAN MANCHU ALI GALI DHA; D; No_Joining_Group
18A2; MONGOLIAN MANCHU ALI GALI SSA; D; No_Joining_Group
18A3; MONGOLIAN MANCHU ALI GALI CYA; D; No_Joining_Group
18A4; MONGOLIAN MANCHU ALI GALI ZHA; D; No_Joining_Group
18A5; MONGOLIAN MANCHU ALI GALI ZA; D; No_Joining_Group
18A6; MONGOLIAN ALI GALI HALF U; D; No_Joining_Group
18A7; MONGOLIAN ALI GALI HALF YA; D; No_Joining_Group
18A8; MONGOLIAN MANCHU ALI GALI BHA; D; No_Joining_Group
18AA; MONGOLIAN MANCHU ALI GALI LHA; D; No_Joining_Group

# Other

200C; ZERO WIDTH NON-JOINER; U; No_Joining_Group
200D; ZERO WIDTH JOINER; C; No_Joining_Group
202F; NARROW NO-BREAK SPACE; U; No_Joining_Group
2066; LEFT-TO-RIGHT ISOLATE; U; No_Joining_Group
2067; RIGHT-TO-LEFT ISOLATE; U; No_Joining_Group
2068; FIRST STRONG ISOLATE; U; No_Joining_Group
2069; POP DIRECTIONAL ISOLATE; U; No_Joining_Group

# Phags-Pa Characters

A840; PHAGS-PA KA; D; No_Joining_Group
A841; PHAGS-PA KHA; D; No_Joining_Group
A842; PHAGS-PA GA; D; No_Joining_Group
A843; PHAGS-PA NGA; D; No_Joining_Group
A844; PHAGS-PA CA; D; No_Joining_Group
A845; PHAGS-PA CHA; D; No_Joining_Group
A846; PHAGS-PA JA; D; No_Joining_Group
A847; PHAGS-PA NYA; D; No_Joining_Group
A848; PHAGS-PA TA; D; No_Joining_Group
A849; PHAGS-PA THA; D; No_Joining_Group
A84A; PHAGS-PA DA; D; No_Joining_Group
A84B; PHAGS-PA NA; D; No_Joining_Group
A84C; PHAGS-PA PA; D; No_Joining_Group
A84D; PHAGS-PA PHA; D; No_Joining_Group
A84E; PHAGS-PA BA; D; No_Joining_Group
A84F; PHAGS-PA MA; D; No_Joining_Group
A850; PHAGS-PA TSA; D; No_Joining_Group
A851; PHAGS-PA TSHA; D; No_Joining_Group
A852; PHAGS-PA DZA; D; No_Joining_Group
A853; PHAGS-PA WA; D; No_Joining_Group
A854; PHAGS-PA ZHA; D; No_Joining_Group
A855; PHAGS-PA ZA; D; No_Joining_Group
A856; PHAGS-PA SMALL A; D; No_Joining_Group
A857; PHAGS-PA YA; D; No_Joining_Group
A858; PHAGS-PA RA; D; No_Joining_Group
A859; PHAGS-PA LA; D; No_Joining_Group
A85A; PHAGS-PA SHA; D; No_Joining_Group
A85B; PHAGS-PA SA; D; No_Joining_Group
A85C; PHAGS-PA HA; D; No_Joining_Group
A85D; PHAGS-PA A; D; No_Joining_Group
A85E; PHAGS-PA I; D; No_Joining_Group
A85F; PHAGS-PA U; D; No_Joining_Group
A860; PHAGS-PA E; D; No_Joining_Group
A861; PHAGS-PA O; D; No_Joining_Group
A862; PHAGS-PA QA; D; No_Joining_Group
A863; PHAGS-PA XA; D; No_Joining_Group
A864; PHAGS-PA FA; D; No_Joining_Group
A865; PHAGS-PA GGA; D; No_Joining_Group
A866; PHAGS-PA EE; D; No_Joining_Group
A867; PHAGS-PA SUBJOINED WA; D; No_Joining_Group
A868; PHAGS-PA SUBJOINED YA; D; No_Joining_Group
A869; PHAGS-PA TTA; D; No_Joining_Group
A86A; PHAGS-PA TTHA; D; No_Joining_Group
A86B; PHAGS-PA DDA; D; No_Joining_Group
A86C; PHAGS-PA NNA; D; No_Joining_Group
A86D; PHAGS-PA ALTERNATE YA; D; No_Joining_Group
A86E; PHAGS-PA VOICELESS SHA; D; No_Joining_Group
A86F; PHAGS-PA VOICED HA; D; No_Joining_Group
A870; PHAGS-PA ASPIRATED FA; D; No_Joining_Group
A871; PHAGS-PA SUBJOINED RA; D; No_Joining_Group
A872; PHAGS-PA SUPERFIXED RA; L; No_Joining_Group
A873; PHAGS-PA CANDRABINDU; U; No_Joining_Group

# Manichaean Characters

10AC0; MANICHAEAN ALEPH; D; MANICHAEAN ALEPH
10AC1; MANICHAEAN BETH; D; MANICHAEAN BETH
10AC2; MANICHAEAN BETH WITH 2 DOTS ABOVE; D; MANICHAEAN BETH
10AC3; MANICHAEAN GIMEL; D; MANICHAEAN GIMEL
10AC4; MANICHAEAN GIMEL WITH ATTACHED RING BELOW; D; MANICHAEAN GIMEL
10AC5; MANICHAEAN DALETH; R; MANICHAEAN DALETH
10AC6; MANICHAEAN HE; U; No_Joining_Group
10AC7; MANICHAEAN WAW; R; MANICHAEAN WAW
10AC8; MANICHAEAN UD; U; No_Joining_Group
10AC9; MANICHAEAN ZAYIN; R; MANICHAEAN ZAYIN
10ACA; MANICHAEAN ZAYIN WITH 2 DOTS ABOVE; R; MANICHAEAN ZAYIN
10ACB; MANICHAEAN JAYIN; U; No_Joining_Group
10ACC; MANICHAEAN JAYIN WITH 2 DOTS ABOVE; U; No_Joining_Group
10ACD; MANICHAEAN HETH; L; MANICHAEAN HETH
10ACE; MANICHAEAN TETH; R; MANICHAEAN TETH
10ACF; MANICHAEAN YODH; R; MANICHAEAN YODH
10AD0; MANICHAEAN KAPH; R; MANICHAEAN KAPH
10AD1; MANICHAEAN KAPH WITH DOT ABOVE; R; MANICHAEAN KAPH
10AD2; MANICHAEAN KAPH WITH 2 DOTS ABOVE; R; MANICHAEAN KAPH
10AD3; MANICHAEAN LAMEDH; D; MANICHAEAN LAMEDH
10AD4; MANICHAEAN DHAMEDH; D; MANICHAEAN DHAMEDH
10AD5; MANICHAEAN THAMEDH; D; MANICHAEAN THAMEDH
10AD6; MANICHAEAN MEM; D; MANICHAEAN MEM
10AD7; MANICHAEAN NUN; L; MANICHAEAN NUN
10AD8; MANICHAEAN SAMEKH; D; MANICHAEAN SAMEKH
10AD9; MANICHAEAN AYIN; D; MANICHAEAN AYIN
10ADA; MANICHAEAN AYIN WITH 2 DOTS ABOVE; D; MANICHAEAN AYIN
10ADB; MANICHAEAN PE; D; MANICHAEAN PE
10ADC; MANICHAEAN PE WITH DOT ABOVE; D; MANICHAEAN PE
10ADD; MANICHAEAN SADHE; R; MANICHAEAN SADHE
10ADE; MANICHAEAN QOPH; D; MANICHAEAN QOPH
10ADF; MANICHAEAN QOPH WITH DOT ABOVE; D; MANICHAEAN QOPH
10AE0; MANICHAEAN QOPH WITH 2 DOTS ABOVE; D; MANICHAEAN QOPH
10AE1; MANICHAEAN RESH; R; MANICHAEAN RESH
10AE2; MANICHAEAN SHIN; U; No_Joining_Group
10AE3; MANICHAEAN SHIN WITH 2 DOTS ABOVE; U; No_Joining_Group
10AE4; MANICHAEAN TAW; R; MANICHAEAN TAW
10AEB; MANICHAEAN ONE; D; MANICHAEAN ONE
10AEC; MANICHAEAN FIVE; D; MANICHAEAN FIVE
10AED; MANICHAEAN TEN; D; MANICHAEAN TEN
10AEE; MANICHAEAN TWENTY; D; MANICHAEAN TWENTY
10AEF; MANICHAEAN HUNDRED; R; MANICHAEAN HUNDRED

# Psalter Pahlavi Characters

10B80; PSALTER PAHLAVI ALEPH; D; No_Joining_Group
10B81; PSALTER PAHLAVI BETH; R; No_Joining_Group
10B82; PSALTER PAHLAVI GIMEL; D; No_Joining_Group
10B83; PSALTER PAHLAVI DALETH; R; No_Joining_Group
10B84; PSALTER PAHLAVI HE; R; No_Joining_Group
10B85; PSALTER PAHLAVI WAW-AYIN-RESH; R; No_Joining_Group
10B86; PSALTER PAHLAVI ZAYIN; D; No_Joining_Group
10B87; PSALTER PAHLAVI HETH; D; No_Joining_Group
10B88; PSALTER PAHLAVI YODH; D; No_Joining_Group
10B89; PSALTER PAHLAVI KAPH; R; No_Joining_Group
10B8A; PSALTER PAHLAVI LAMEDH; D; No_Joining_Group
10B8B; PSALTER PAHLAVI MEM-QOPH; D; No_Joining_Group
10B8C; PSALTER PAHLAVI NUN; R; No_Joining_Group
10B8D; PSALTER PAHLAVI SAMEKH; D; No_Joining_Group
10B8E; PSALTER PAHLAVI PE; R; No_Joining_Group
10B8F; PSALTER PAHLAVI SADHE; R; No_Joining_Group
10B90; PSALTER PAHLAVI SHIN; D; No_Joining_Group
10B91; PSALTER PAHLAVI TAW; R; No_Joining_Group
10BA9; PSALTER PAHLAVI ONE; R; No_Joining_Group
10BAA; PSALTER PAHLAVI TWO; R; No_Joining_Group
10BAB; PSALTER PAHLAVI THREE; R; No_Joining_Group
10BAC; PSALTER PAHLAVI FOUR; R; No_Joining_Group
10BAD; PSALTER PAHLAVI TEN; D; No_Joining_Group
10BAE; PSALTER PAHLAVI TWENTY; D; No_Joining_Group
10BAF; PSALTER PAHLAVI HUNDRED; U; No_Joining_Group

# Hanifi Rohingya Characters

10D00; HANIFI ROHINGYA A; L; No_Joining_Group
10D01; HANIFI ROHINGYA BA; D; No_Joining_Group
10D02; HANIFI ROHINGYA PA; D; HANIFI ROHINGYA PA
10D03; HANIFI ROHINGYA TA; D; No_Joining_Group
10D04; HANIFI ROHINGYA TTA; D; No_Joining_Group
10D05; HANIFI ROHINGYA JA; D; No_Joining_Group
10D06; HANIFI ROHINGYA CA; D; No_Joining_Group
10D07; HANIFI ROHINGYA HA; D; No_Joining_Group
10D08; HANIFI ROHINGYA KHA; D; No_Joining_Group
10D09; HANIFI ROHINGYA PA WITH DOT ABOVE; D; HANIFI ROHINGYA PA
10D0A; HANIFI ROHINGYA DA; D; No_Joining_Group
10D0B; HANIFI ROHINGYA DDA; D; No_Joining_Group
10D0C; HANIFI ROHINGYA RA; D; No_Joining_Group
10D0D; HANIFI ROHINGYA RRA; D; No_Joining_Group
10D0E; HANIFI ROHINGYA ZA; D; No_Joining_Group
10D0F; HANIFI ROHINGYA SA; D; No_Joining_Group
10D10; HANIFI ROHINGYA SHA; D; No_Joining_Group
10D11; HANIFI ROHINGYA KA; D; No_Joining_Group
10D12; HANIFI ROHINGYA GA; D; No_Joining_Group
10D13; HANIFI ROHINGYA LA; D; No_Joining_Group
10D14; HANIFI ROHINGYA MA; D; No_Joining_Group
10D15; HANIFI ROHINGYA NA; D; No_Joining_Group
10D16; HANIFI ROHINGYA WA; D; No_Joining_Group
10D17; HANIFI ROHINGYA KINNA WA; D; No_Joining_Group
10D18; HANIFI ROHINGYA YA; D; No_Joining_Group
10D19; HANIFI ROHINGYA KINNA YA; D; HANIFI ROHINGYA KINNA YA
10D1A; HANIFI ROHINGYA NGA; D; No_Joining_Group
10D1B; HANIFI ROHINGYA NYA; D; No_Joining_Group
10D1C; HANIFI ROHINGYA PA WITH 3 DOTS ABOVE; D; HANIFI ROHINGYA PA
10D1D; HANIFI ROHINGYA VOWEL A; D; No_Joining_Group
10D1E; HANIFI ROHINGYA DOTLESS KINNA YA WITH LEFT-FACING HOOK BELOW; D; HANIFI ROHINGYA KINNA YA
10D1F; HANIFI ROHINGYA VOWEL U; D; No_Joining_Group
10D20; HANIFI ROHINGYA DOTLESS KINNA YA WITH RIGHT-FACING HOOK BELOW; D; HANIFI ROHINGYA KINNA YA
10D21; HANIFI ROHINGYA VOWEL O; D; No_Joining_Group
10D22; HANIFI ROHINGYA SAKIN; R; No_Joining_Group
10D23; HANIFI ROHINGYA DOTLESS KINNA YA WITH DOT ABOVE; D; HANIFI ROHINGYA KINNA YA

# Arabic Extended-C Characters

10EC2; DAL WITH VERTICAL 2 DOTS BELOW; R; DAL
10EC3; TAH WITH VERTICAL 2 DOTS BELOW; D; TAH
10EC4; KAF WITH VERTICAL 2 DOTS BELOW; D; KAF

# Sogdian Characters

10F30; SOGDIAN ALEPH; D; No_Joining_Group
10F31; SOGDIAN BETH; D; No_Joining_Group
10F32; SOGDIAN GIMEL; D; No_Joining_Group
10F33; SOGDIAN HE; R; No_Joining_Group
10F34; SOGDIAN WAW; D; No_Joining_Group
10F35; SOGDIAN ZAYIN; D; No_Joining_Group
10F36; SOGDIAN HETH; D; No_Joining_Group
10F37; SOGDIAN YODH; D; No_Joining_Group
10F38; SOGDIAN KAPH; D; No_Joining_Group
10F39; SOGDIAN LAMEDH; D; No_Joining_Group
10F3A; SOGDIAN MEM; D; No_Joining_Group
10F3B; SOGDIAN NUN; D; No_Joining_Group
10F3C; SOGDIAN SAMEKH; D; No_Joining_Group
10F3D; SOGDIAN AYIN; D; No_Joining_Group
10F3E; SOGDIAN PE; D; No_Joining_Group
10F3F; SOGDIAN SADHE; D; No_Joining_Group
10F40; SOGDIAN RESH-AYIN; D; No_Joining_Group
10F41; SOGDIAN SHIN; D; No_Joining_Group
10F42; SOGDIAN TAW; D; No_Joining_Group
10F43; SOGDIAN FETH; D; No_Joining_Group
10F44; SOGDIAN LESH; D; No_Joining_Group
10F45; SOGDIAN INDEPENDENT SHIN; U; No_Joining_Group
10F51; SOGDIAN ONE; D; No_Joining_Group
10F52; SOGDIAN TEN; D; No_Joining_Group
10F53; SOGDIAN TWENTY; D; No_Joining_Group
10F54; SOGDIAN ONE HUNDRED; R; No_Joining_Group

# Old Uyghur Characters

10F70; OLD UYGHUR ALEPH; D; No_Joining_Group
10F71; OLD UYGHUR BETH; D; No_Joining_Group
10F72; OLD UYGHUR GIMEL-HETH; D; No_Joining_Group
10F73; OLD UYGHUR WAW; D; No_Joining_Group
10F74; OLD UYGHUR ZAYIN; R; No_Joining_Group
10F75; OLD UYGHUR FINAL HETH; R; No_Joining_Group
10F76; OLD UYGHUR YODH; D; No_Joining_Group
10F77; OLD UYGHUR KAPH; D; No_Joining_Group
10F78; OLD UYGHUR LAMEDH; D; No_Joining_Group
10F79; OLD UYGHUR MEM; D; No_Joining_Group
10F7A; OLD UYGHUR NUN; D; No_Joining_Group
10F7B; OLD UYGHUR SAMEKH; D; No_Joining_Group
10F7C; OLD UYGHUR PE; D; No_Joining_Group
10F7D; OLD UYGHUR SADHE; D; No_Joining_Group
10F7E; OLD UYGHUR RESH; D; No_Joining_Group
10F7F; OLD UYGHUR SHIN; D; No_Joining_Group
10F80; OLD UYGHUR TAW; D; No_Joining_Group
10F81; OLD UYGHUR LESH; D; No_Joining_Group

# Chorasmian Characters

10FB0; CHORASMIAN ALEPH; D; No_Joining_Group
10FB1; CHORASMIAN SMALL ALEPH; U; No_Joining_Group
10FB2; CHORASMIAN BETH; D; No_Joining_Group
10FB3; CHORASMIAN GIMEL; D; No_Joining_Group
10FB4; CHORASMIAN DALETH; R; No_Joining_Group
10FB5; CHORASMIAN HE; R; No_Joining_Group
10FB6; CHORASMIAN WAW; R; No_Joining_Group
10FB7; CHORASMIAN CURLED WAW; U; No_Joining_Group
10FB8; CHORASMIAN ZAYIN; D; No_Joining_Group
10FB9; CHORASMIAN HETH; R; No_Joining_Group
10FBA; CHORASMIAN YODH; R; No_Joining_Group
10FBB; CHORASMIAN KAPH; D; No_Joining_Group
10FBC; CHORASMIAN LAMEDH; D; No_Joining_Group
10FBD; CHORASMIAN MEM; R; No_Joining_Group
10FBE; CHORASMIAN NUN; D; No_Joining_Group
10FBF; CHORASMIAN SAMEKH; D; No_Joining_Group
10FC0; CHORASMIAN AYIN; U; No_Joining_Group
10FC1; CHORASMIAN PE; D; No_Joining_Group
10FC2; CHORASMIAN RESH; R; No_Joining_Group
10FC3; CHORASMIAN SHIN; R; No_Joining_Group
10FC4; CHORASMIAN TAW; D; No_Joining_Group
10FC5; CHORASMIAN ONE; U; No_Joining_Group
10FC6; CHORASMIAN TWO; U; No_Joining_Group
10FC7; CHORASMIAN THREE; U; No_Joining_Group
10FC8; CHORASMIAN FOUR; U; No_Joining_Group
10FC9; CHORASMIAN TEN; R; No_Joining_Group
10FCA; CHORASMIAN TWENTY; D; No_Joining_Group
10FCB; CHORASMIAN ONE HUNDRED; L; No_Joining_Group

# Kaithi Number Signs
# These are prepended concatenation marks, comparable
# to the number signs in the Arabic script.
# Listed here for consistency in property values.

110BD; KAITHI NUMBER SIGN; U; No_Joining_Group
110CD; KAITHI NUMBER SIGN ABOVE; U; No_Joining_Group

# Adlam Characters

1E900;ADLAM CAPITAL ALIF; D; No_Joining_Group
1E901;ADLAM CAPITAL DAALI; D; No_Joining_Group
1E902;ADLAM CAPITAL LAAM; D; No_Joining_Group
1E903;ADLAM CAPITAL MIIM; D; No_Joining_Group
1E904;ADLAM CAPITAL BA; D; No_Joining_Group
1E905;ADLAM CAPITAL SINNYIIYHE; D; No_Joining_Group
1E906;ADLAM CAPITAL PE; D; No_Joining_Group
1E907;ADLAM CAPITAL BHE; D; No_Joining_Group
1E908;ADLAM CAPITAL RA; D; No_Joining_Group
1E909;ADLAM CAPITAL E; D; No_Joining_Group
1E90A;ADLAM CAPITAL FA; D; No_Joining_Group
1E90B;ADLAM CAPITAL I; D; No_Joining_Group
1E90C;ADLAM CAPITAL O; D; No_Joining_Group
1E90D;ADLAM CAPITAL DHA; D; No_Joining_Group
1E90E;ADLAM CAPITAL YHE; D; No_Joining_Group
1E90F;ADLAM CAPITAL WAW; D; No_Joining_Group
1E910;ADLAM CAPITAL NUN; D; No_Joining_Group
1E911;ADLAM CAPITAL KAF; D; No_Joining_Group
1E912;ADLAM CAPITAL YA; D; No_Joining_Group
1E913;ADLAM CAPITAL U; D; No_Joining_Group
1E914;ADLAM CAPITAL JIIM; D; No_Joining_Group
1E915;ADLAM CAPITAL CHI; D; No_Joining_Group
1E916;ADLAM CAPITAL HA; D; No_Joining_Group
1E917;ADLAM CAPITAL QAAF; D; No_Joining_Group
1E918;ADLAM CAPITAL GA; D; No_Joining_Group
1E919;ADLAM CAPITAL NYA; D; No_Joining_Group
1E91A;ADLAM CAPITAL TU; D; No_Joining_Group
1E91B;ADLAM CAPITAL NHA; D; No_Joining_Group
1E91C;ADLAM CAPITAL VA; D; No_Joining_Group
1E91D;ADLAM CAPITAL KHA; D; No_Joining_Group
1E91E;ADLAM CAPITAL GBE; D; No_Joining_Group
1E91F;ADLAM CAPITAL ZAL; D; No_Joining_Group
1E920;ADLAM CAPITAL KPO; D; No_Joining_Group
1E921;ADLAM CAPITAL SHA; D; No_Joining_Group
1E922;ADLAM SMALL ALIF; D; No_Joining_Group
1E923;ADLAM SMALL DAALI; D; No_Joining_Group
1E924;ADLAM SMALL LAAM; D; No_Joining_Group
1E925;ADLAM SMALL MIIM; D; No_Joining_Group
1E926;ADLAM SMALL BA; D; No_Joining_Group
1E927;ADLAM SMALL SINNYIIYHE; D; No_Joining_Group
1E928;ADLAM SMALL PE; D; No_Joining_Group
1E929;ADLAM SMALL BHE; D; No_Joining_Group
1E92A;ADLAM SMALL RA; D; No_Joining_Group
1E92B;ADLAM SMALL E; D; No_Joining_Group
1E92C;ADLAM SMALL FA; D; No_Joining_Group
1E92D;ADLAM SMALL I; D; No_Joining_Group
1E92E;ADLAM SMALL O; D; No_Joining_Group
1E92F;ADLAM SMALL DHA; D; No_Joining_Group
1E930;ADLAM SMALL YHE; D; No_Joining_Group
1E931;ADLAM SMALL WAW; D; No_Joining_Group
1E932;ADLAM SMALL NUN; D; No_Joining_Group
1E933;ADLAM SMALL KAF; D; No_Joining_Group
1E934;ADLAM SMALL YA; D; No_Joining_Group
1E935;ADLAM SMALL U; D; No_Joining_Group
1E936;ADLAM SMALL JIIM; D; No_Joining_Group
1E937;ADLAM SMALL CHI; D; No_Joining_Group
1E938;ADLAM SMALL HA; D; No_Joining_Group
1E939;ADLAM SMALL QAAF; D; No_Joining_Group
1E93A;ADLAM SMALL GA; D; No_Joining_Group
1E93B;ADLAM SMALL NYA; D; No_Joining_Group
1E93C;ADLAM SMALL TU; D; No_Joining_Group
1E93D;ADLAM SMALL NHA; D; No_Joining_Group
1E93E;ADLAM SMALL VA; D; No_Joining_Group
1E93F;ADLAM SMALL KHA; D; No_Joining_Group
1E940;ADLAM SMALL GBE; D; No_Joining_Group
1E941;ADLAM SMALL ZAL; D; No_Joining_Group
1E942;ADLAM SMALL KPO; D; No_Joining_Group
1E943;ADLAM SMALL SHA; D; No_Joining_Group
1E94B;ADLAM NASALIZATION MARK; T; No_Joining_Group

# EOF`
// Some Transparent Characters are listed here
let derived_shaping = `

# from https://www.unicode.org/Public/16.0.0/ucd/extracted/DerivedJoiningType.txt
# DerivedJoiningType-16.0.0.txt
# Date: 2024-04-30, 21:48:18 GMT
# © 2024 Unicode®, Inc.
# Unicode and the Unicode Logo are registered trademarks of Unicode, Inc. in the U.S. and other countries.
# For terms of use and license, see https://www.unicode.org/terms_of_use.html
#
# Unicode Character Database
#   For documentation, see https://www.unicode.org/reports/tr44/

# ================================================

#	Type T is derived, as described in ArabicShaping.txt

#  All code points not explicitly listed for Joining_Type
#  have the value Non_Joining (U).

# @missing: 0000..10FFFF; Non_Joining

# ================================================

# Joining_Type=Join_Causing

0640          ; C # Lm       ARABIC TATWEEL
07FA          ; C # Lm       NKO LAJANYALAN
0883..0885    ; C # Lo   [3] ARABIC TATWEEL WITH OVERSTRUCK HAMZA..ARABIC TATWEEL WITH TWO DOTS BELOW
180A          ; C # Po       MONGOLIAN NIRUGU
200D          ; C # Cf       ZERO WIDTH JOINER

# Total code points: 7

# ================================================

# Joining_Type=Dual_Joining

0620          ; D # Lo       ARABIC LETTER KASHMIRI YEH
0626          ; D # Lo       ARABIC LETTER YEH WITH HAMZA ABOVE
0628          ; D # Lo       ARABIC LETTER BEH
062A..062E    ; D # Lo   [5] ARABIC LETTER TEH..ARABIC LETTER KHAH
0633..063F    ; D # Lo  [13] ARABIC LETTER SEEN..ARABIC LETTER FARSI YEH WITH THREE DOTS ABOVE
0641..0647    ; D # Lo   [7] ARABIC LETTER FEH..ARABIC LETTER HEH
0649..064A    ; D # Lo   [2] ARABIC LETTER ALEF MAKSURA..ARABIC LETTER YEH
066E..066F    ; D # Lo   [2] ARABIC LETTER DOTLESS BEH..ARABIC LETTER DOTLESS QAF
0678..0687    ; D # Lo  [16] ARABIC LETTER HIGH HAMZA YEH..ARABIC LETTER TCHEHEH
069A..06BF    ; D # Lo  [38] ARABIC LETTER SEEN WITH DOT BELOW AND DOT ABOVE..ARABIC LETTER TCHEH WITH DOT ABOVE
06C1..06C2    ; D # Lo   [2] ARABIC LETTER HEH GOAL..ARABIC LETTER HEH GOAL WITH HAMZA ABOVE
06CC          ; D # Lo       ARABIC LETTER FARSI YEH
06CE          ; D # Lo       ARABIC LETTER YEH WITH SMALL V
06D0..06D1    ; D # Lo   [2] ARABIC LETTER E..ARABIC LETTER YEH WITH THREE DOTS BELOW
06FA..06FC    ; D # Lo   [3] ARABIC LETTER SHEEN WITH DOT BELOW..ARABIC LETTER GHAIN WITH DOT BELOW
06FF          ; D # Lo       ARABIC LETTER HEH WITH INVERTED V
0712..0714    ; D # Lo   [3] SYRIAC LETTER BETH..SYRIAC LETTER GAMAL GARSHUNI
071A..071D    ; D # Lo   [4] SYRIAC LETTER HETH..SYRIAC LETTER YUDH
071F..0727    ; D # Lo   [9] SYRIAC LETTER KAPH..SYRIAC LETTER REVERSED PE
0729          ; D # Lo       SYRIAC LETTER QAPH
072B          ; D # Lo       SYRIAC LETTER SHIN
072D..072E    ; D # Lo   [2] SYRIAC LETTER PERSIAN BHETH..SYRIAC LETTER PERSIAN GHAMAL
074E..0758    ; D # Lo  [11] SYRIAC LETTER SOGDIAN KHAPH..ARABIC LETTER HAH WITH THREE DOTS POINTING UPWARDS BELOW
075C..076A    ; D # Lo  [15] ARABIC LETTER SEEN WITH FOUR DOTS ABOVE..ARABIC LETTER LAM WITH BAR
076D..0770    ; D # Lo   [4] ARABIC LETTER SEEN WITH TWO DOTS VERTICALLY ABOVE..ARABIC LETTER SEEN WITH SMALL ARABIC LETTER TAH AND TWO DOTS
0772          ; D # Lo       ARABIC LETTER HAH WITH SMALL ARABIC LETTER TAH ABOVE
0775..0777    ; D # Lo   [3] ARABIC LETTER FARSI YEH WITH EXTENDED ARABIC-INDIC DIGIT TWO ABOVE..ARABIC LETTER FARSI YEH WITH EXTENDED ARABIC-INDIC DIGIT FOUR BELOW
077A..077F    ; D # Lo   [6] ARABIC LETTER YEH BARREE WITH EXTENDED ARABIC-INDIC DIGIT TWO ABOVE..ARABIC LETTER KAF WITH TWO DOTS ABOVE
07CA..07EA    ; D # Lo  [33] NKO LETTER A..NKO LETTER JONA RA
0841..0845    ; D # Lo   [5] MANDAIC LETTER AB..MANDAIC LETTER USHENNA
0848          ; D # Lo       MANDAIC LETTER ATT
084A..0853    ; D # Lo  [10] MANDAIC LETTER AK..MANDAIC LETTER AR
0855          ; D # Lo       MANDAIC LETTER AT
0860          ; D # Lo       SYRIAC LETTER MALAYALAM NGA
0862..0865    ; D # Lo   [4] SYRIAC LETTER MALAYALAM NYA..SYRIAC LETTER MALAYALAM NNNA
0868          ; D # Lo       SYRIAC LETTER MALAYALAM LLA
0886          ; D # Lo       ARABIC LETTER THIN YEH
0889..088D    ; D # Lo   [5] ARABIC LETTER NOON WITH INVERTED SMALL V..ARABIC LETTER KEHEH WITH TWO DOTS VERTICALLY BELOW
08A0..08A9    ; D # Lo  [10] ARABIC LETTER BEH WITH SMALL V BELOW..ARABIC LETTER YEH WITH TWO DOTS BELOW AND DOT ABOVE
08AF..08B0    ; D # Lo   [2] ARABIC LETTER SAD WITH THREE DOTS BELOW..ARABIC LETTER GAF WITH INVERTED STROKE
08B3..08B8    ; D # Lo   [6] ARABIC LETTER AIN WITH THREE DOTS BELOW..ARABIC LETTER TEH WITH SMALL TEH ABOVE
08BA..08C8    ; D # Lo  [15] ARABIC LETTER YEH WITH TWO DOTS BELOW AND SMALL NOON ABOVE..ARABIC LETTER GRAF
1807          ; D # Po       MONGOLIAN SIBE SYLLABLE BOUNDARY MARKER
1820..1842    ; D # Lo  [35] MONGOLIAN LETTER A..MONGOLIAN LETTER CHI
1843          ; D # Lm       MONGOLIAN LETTER TODO LONG VOWEL SIGN
1844..1878    ; D # Lo  [53] MONGOLIAN LETTER TODO E..MONGOLIAN LETTER CHA WITH TWO DOTS
1887..18A8    ; D # Lo  [34] MONGOLIAN LETTER ALI GALI A..MONGOLIAN LETTER MANCHU ALI GALI BHA
18AA          ; D # Lo       MONGOLIAN LETTER MANCHU ALI GALI LHA
A840..A871    ; D # Lo  [50] PHAGS-PA LETTER KA..PHAGS-PA SUBJOINED LETTER RA
10AC0..10AC4  ; D # Lo   [5] MANICHAEAN LETTER ALEPH..MANICHAEAN LETTER GHIMEL
10AD3..10AD6  ; D # Lo   [4] MANICHAEAN LETTER LAMEDH..MANICHAEAN LETTER MEM
10AD8..10ADC  ; D # Lo   [5] MANICHAEAN LETTER SAMEKH..MANICHAEAN LETTER FE
10ADE..10AE0  ; D # Lo   [3] MANICHAEAN LETTER QOPH..MANICHAEAN LETTER QHOPH
10AEB..10AEE  ; D # No   [4] MANICHAEAN NUMBER ONE..MANICHAEAN NUMBER TWENTY
10B80         ; D # Lo       PSALTER PAHLAVI LETTER ALEPH
10B82         ; D # Lo       PSALTER PAHLAVI LETTER GIMEL
10B86..10B88  ; D # Lo   [3] PSALTER PAHLAVI LETTER ZAYIN..PSALTER PAHLAVI LETTER YODH
10B8A..10B8B  ; D # Lo   [2] PSALTER PAHLAVI LETTER LAMEDH..PSALTER PAHLAVI LETTER MEM-QOPH
10B8D         ; D # Lo       PSALTER PAHLAVI LETTER SAMEKH
10B90         ; D # Lo       PSALTER PAHLAVI LETTER SHIN
10BAD..10BAE  ; D # No   [2] PSALTER PAHLAVI NUMBER TEN..PSALTER PAHLAVI NUMBER TWENTY
10D01..10D21  ; D # Lo  [33] HANIFI ROHINGYA LETTER BA..HANIFI ROHINGYA VOWEL O
10D23         ; D # Lo       HANIFI ROHINGYA MARK NA KHONNA
10EC3..10EC4  ; D # Lo   [2] ARABIC LETTER TAH WITH TWO DOTS VERTICALLY BELOW..ARABIC LETTER KAF WITH TWO DOTS VERTICALLY BELOW
10F30..10F32  ; D # Lo   [3] SOGDIAN LETTER ALEPH..SOGDIAN LETTER GIMEL
10F34..10F44  ; D # Lo  [17] SOGDIAN LETTER WAW..SOGDIAN LETTER LESH
10F51..10F53  ; D # No   [3] SOGDIAN NUMBER ONE..SOGDIAN NUMBER TWENTY
10F70..10F73  ; D # Lo   [4] OLD UYGHUR LETTER ALEPH..OLD UYGHUR LETTER WAW
10F76..10F81  ; D # Lo  [12] OLD UYGHUR LETTER YODH..OLD UYGHUR LETTER LESH
10FB0         ; D # Lo       CHORASMIAN LETTER ALEPH
10FB2..10FB3  ; D # Lo   [2] CHORASMIAN LETTER BETH..CHORASMIAN LETTER GIMEL
10FB8         ; D # Lo       CHORASMIAN LETTER ZAYIN
10FBB..10FBC  ; D # Lo   [2] CHORASMIAN LETTER KAPH..CHORASMIAN LETTER LAMEDH
10FBE..10FBF  ; D # Lo   [2] CHORASMIAN LETTER NUN..CHORASMIAN LETTER SAMEKH
10FC1         ; D # Lo       CHORASMIAN LETTER PE
10FC4         ; D # Lo       CHORASMIAN LETTER TAW
10FCA         ; D # No       CHORASMIAN NUMBER TWENTY
1E900..1E943  ; D # L&  [68] ADLAM CAPITAL LETTER ALIF..ADLAM SMALL LETTER SHA

# Total code points: 612

# ================================================

# Joining_Type=Right_Joining

0622..0625    ; R # Lo   [4] ARABIC LETTER ALEF WITH MADDA ABOVE..ARABIC LETTER ALEF WITH HAMZA BELOW
0627          ; R # Lo       ARABIC LETTER ALEF
0629          ; R # Lo       ARABIC LETTER TEH MARBUTA
062F..0632    ; R # Lo   [4] ARABIC LETTER DAL..ARABIC LETTER ZAIN
0648          ; R # Lo       ARABIC LETTER WAW
0671..0673    ; R # Lo   [3] ARABIC LETTER ALEF WASLA..ARABIC LETTER ALEF WITH WAVY HAMZA BELOW
0675..0677    ; R # Lo   [3] ARABIC LETTER HIGH HAMZA ALEF..ARABIC LETTER U WITH HAMZA ABOVE
0688..0699    ; R # Lo  [18] ARABIC LETTER DDAL..ARABIC LETTER REH WITH FOUR DOTS ABOVE
06C0          ; R # Lo       ARABIC LETTER HEH WITH YEH ABOVE
06C3..06CB    ; R # Lo   [9] ARABIC LETTER TEH MARBUTA GOAL..ARABIC LETTER VE
06CD          ; R # Lo       ARABIC LETTER YEH WITH TAIL
06CF          ; R # Lo       ARABIC LETTER WAW WITH DOT ABOVE
06D2..06D3    ; R # Lo   [2] ARABIC LETTER YEH BARREE..ARABIC LETTER YEH BARREE WITH HAMZA ABOVE
06D5          ; R # Lo       ARABIC LETTER AE
06EE..06EF    ; R # Lo   [2] ARABIC LETTER DAL WITH INVERTED V..ARABIC LETTER REH WITH INVERTED V
0710          ; R # Lo       SYRIAC LETTER ALAPH
0715..0719    ; R # Lo   [5] SYRIAC LETTER DALATH..SYRIAC LETTER ZAIN
071E          ; R # Lo       SYRIAC LETTER YUDH HE
0728          ; R # Lo       SYRIAC LETTER SADHE
072A          ; R # Lo       SYRIAC LETTER RISH
072C          ; R # Lo       SYRIAC LETTER TAW
072F          ; R # Lo       SYRIAC LETTER PERSIAN DHALATH
074D          ; R # Lo       SYRIAC LETTER SOGDIAN ZHAIN
0759..075B    ; R # Lo   [3] ARABIC LETTER DAL WITH TWO DOTS VERTICALLY BELOW AND SMALL TAH..ARABIC LETTER REH WITH STROKE
076B..076C    ; R # Lo   [2] ARABIC LETTER REH WITH TWO DOTS VERTICALLY ABOVE..ARABIC LETTER REH WITH HAMZA ABOVE
0771          ; R # Lo       ARABIC LETTER REH WITH SMALL ARABIC LETTER TAH AND TWO DOTS
0773..0774    ; R # Lo   [2] ARABIC LETTER ALEF WITH EXTENDED ARABIC-INDIC DIGIT TWO ABOVE..ARABIC LETTER ALEF WITH EXTENDED ARABIC-INDIC DIGIT THREE ABOVE
0778..0779    ; R # Lo   [2] ARABIC LETTER WAW WITH EXTENDED ARABIC-INDIC DIGIT TWO ABOVE..ARABIC LETTER WAW WITH EXTENDED ARABIC-INDIC DIGIT THREE ABOVE
0840          ; R # Lo       MANDAIC LETTER HALQA
0846..0847    ; R # Lo   [2] MANDAIC LETTER AZ..MANDAIC LETTER IT
0849          ; R # Lo       MANDAIC LETTER AKSA
0854          ; R # Lo       MANDAIC LETTER ASH
0856..0858    ; R # Lo   [3] MANDAIC LETTER DUSHENNA..MANDAIC LETTER AIN
0867          ; R # Lo       SYRIAC LETTER MALAYALAM RA
0869..086A    ; R # Lo   [2] SYRIAC LETTER MALAYALAM LLLA..SYRIAC LETTER MALAYALAM SSA
0870..0882    ; R # Lo  [19] ARABIC LETTER ALEF WITH ATTACHED FATHA..ARABIC LETTER ALEF WITH ATTACHED LEFT HAMZA
088E          ; R # Lo       ARABIC VERTICAL TAIL
08AA..08AC    ; R # Lo   [3] ARABIC LETTER REH WITH LOOP..ARABIC LETTER ROHINGYA YEH
08AE          ; R # Lo       ARABIC LETTER DAL WITH THREE DOTS BELOW
08B1..08B2    ; R # Lo   [2] ARABIC LETTER STRAIGHT WAW..ARABIC LETTER ZAIN WITH INVERTED V ABOVE
08B9          ; R # Lo       ARABIC LETTER REH WITH SMALL NOON ABOVE
10AC5         ; R # Lo       MANICHAEAN LETTER DALETH
10AC7         ; R # Lo       MANICHAEAN LETTER WAW
10AC9..10ACA  ; R # Lo   [2] MANICHAEAN LETTER ZAYIN..MANICHAEAN LETTER ZHAYIN
10ACE..10AD2  ; R # Lo   [5] MANICHAEAN LETTER TETH..MANICHAEAN LETTER KHAPH
10ADD         ; R # Lo       MANICHAEAN LETTER SADHE
10AE1         ; R # Lo       MANICHAEAN LETTER RESH
10AE4         ; R # Lo       MANICHAEAN LETTER TAW
10AEF         ; R # No       MANICHAEAN NUMBER ONE HUNDRED
10B81         ; R # Lo       PSALTER PAHLAVI LETTER BETH
10B83..10B85  ; R # Lo   [3] PSALTER PAHLAVI LETTER DALETH..PSALTER PAHLAVI LETTER WAW-AYIN-RESH
10B89         ; R # Lo       PSALTER PAHLAVI LETTER KAPH
10B8C         ; R # Lo       PSALTER PAHLAVI LETTER NUN
10B8E..10B8F  ; R # Lo   [2] PSALTER PAHLAVI LETTER PE..PSALTER PAHLAVI LETTER SADHE
10B91         ; R # Lo       PSALTER PAHLAVI LETTER TAW
10BA9..10BAC  ; R # No   [4] PSALTER PAHLAVI NUMBER ONE..PSALTER PAHLAVI NUMBER FOUR
10D22         ; R # Lo       HANIFI ROHINGYA MARK SAKIN
10EC2         ; R # Lo       ARABIC LETTER DAL WITH TWO DOTS VERTICALLY BELOW
10F33         ; R # Lo       SOGDIAN LETTER HE
10F54         ; R # No       SOGDIAN NUMBER ONE HUNDRED
10F74..10F75  ; R # Lo   [2] OLD UYGHUR LETTER ZAYIN..OLD UYGHUR LETTER FINAL HETH
10FB4..10FB6  ; R # Lo   [3] CHORASMIAN LETTER DALETH..CHORASMIAN LETTER WAW
10FB9..10FBA  ; R # Lo   [2] CHORASMIAN LETTER HETH..CHORASMIAN LETTER YODH
10FBD         ; R # Lo       CHORASMIAN LETTER MEM
10FC2..10FC3  ; R # Lo   [2] CHORASMIAN LETTER RESH..CHORASMIAN LETTER SHIN
10FC9         ; R # No       CHORASMIAN NUMBER TEN

# Total code points: 153

# ================================================

# Joining_Type=Left_Joining

A872          ; L # Lo       PHAGS-PA SUPERFIXED LETTER RA
10ACD         ; L # Lo       MANICHAEAN LETTER HETH
10AD7         ; L # Lo       MANICHAEAN LETTER NUN
10D00         ; L # Lo       HANIFI ROHINGYA LETTER A
10FCB         ; L # No       CHORASMIAN NUMBER ONE HUNDRED

# Total code points: 5

# ================================================

# Joining_Type=Transparent

00AD          ; T # Cf       SOFT HYPHEN
0300..036F    ; T # Mn [112] COMBINING GRAVE ACCENT..COMBINING LATIN SMALL LETTER X
0483..0487    ; T # Mn   [5] COMBINING CYRILLIC TITLO..COMBINING CYRILLIC POKRYTIE
0488..0489    ; T # Me   [2] COMBINING CYRILLIC HUNDRED THOUSANDS SIGN..COMBINING CYRILLIC MILLIONS SIGN
0591..05BD    ; T # Mn  [45] HEBREW ACCENT ETNAHTA..HEBREW POINT METEG
05BF          ; T # Mn       HEBREW POINT RAFE
05C1..05C2    ; T # Mn   [2] HEBREW POINT SHIN DOT..HEBREW POINT SIN DOT
05C4..05C5    ; T # Mn   [2] HEBREW MARK UPPER DOT..HEBREW MARK LOWER DOT
05C7          ; T # Mn       HEBREW POINT QAMATS QATAN
0610..061A    ; T # Mn  [11] ARABIC SIGN SALLALLAHOU ALAYHE WASSALLAM..ARABIC SMALL KASRA
061C          ; T # Cf       ARABIC LETTER MARK
064B..065F    ; T # Mn  [21] ARABIC FATHATAN..ARABIC WAVY HAMZA BELOW
0670          ; T # Mn       ARABIC LETTER SUPERSCRIPT ALEF
06D6..06DC    ; T # Mn   [7] ARABIC SMALL HIGH LIGATURE SAD WITH LAM WITH ALEF MAKSURA..ARABIC SMALL HIGH SEEN
06DF..06E4    ; T # Mn   [6] ARABIC SMALL HIGH ROUNDED ZERO..ARABIC SMALL HIGH MADDA
06E7..06E8    ; T # Mn   [2] ARABIC SMALL HIGH YEH..ARABIC SMALL HIGH NOON
06EA..06ED    ; T # Mn   [4] ARABIC EMPTY CENTRE LOW STOP..ARABIC SMALL LOW MEEM
070F          ; T # Cf       SYRIAC ABBREVIATION MARK
0711          ; T # Mn       SYRIAC LETTER SUPERSCRIPT ALAPH
0730..074A    ; T # Mn  [27] SYRIAC PTHAHA ABOVE..SYRIAC BARREKH
07A6..07B0    ; T # Mn  [11] THAANA ABAFILI..THAANA SUKUN
07EB..07F3    ; T # Mn   [9] NKO COMBINING SHORT HIGH TONE..NKO COMBINING DOUBLE DOT ABOVE
07FD          ; T # Mn       NKO DANTAYALAN
0816..0819    ; T # Mn   [4] SAMARITAN MARK IN..SAMARITAN MARK DAGESH
081B..0823    ; T # Mn   [9] SAMARITAN MARK EPENTHETIC YUT..SAMARITAN VOWEL SIGN A
0825..0827    ; T # Mn   [3] SAMARITAN VOWEL SIGN SHORT A..SAMARITAN VOWEL SIGN U
0829..082D    ; T # Mn   [5] SAMARITAN VOWEL SIGN LONG I..SAMARITAN MARK NEQUDAA
0859..085B    ; T # Mn   [3] MANDAIC AFFRICATION MARK..MANDAIC GEMINATION MARK
0897..089F    ; T # Mn   [9] ARABIC PEPET..ARABIC HALF MADDA OVER MADDA
08CA..08E1    ; T # Mn  [24] ARABIC SMALL HIGH FARSI YEH..ARABIC SMALL HIGH SIGN SAFHA
08E3..0902    ; T # Mn  [32] ARABIC TURNED DAMMA BELOW..DEVANAGARI SIGN ANUSVARA
093A          ; T # Mn       DEVANAGARI VOWEL SIGN OE
093C          ; T # Mn       DEVANAGARI SIGN NUKTA
0941..0948    ; T # Mn   [8] DEVANAGARI VOWEL SIGN U..DEVANAGARI VOWEL SIGN AI
094D          ; T # Mn       DEVANAGARI SIGN VIRAMA
0951..0957    ; T # Mn   [7] DEVANAGARI STRESS SIGN UDATTA..DEVANAGARI VOWEL SIGN UUE
0962..0963    ; T # Mn   [2] DEVANAGARI VOWEL SIGN VOCALIC L..DEVANAGARI VOWEL SIGN VOCALIC LL
0981          ; T # Mn       BENGALI SIGN CANDRABINDU
09BC          ; T # Mn       BENGALI SIGN NUKTA
09C1..09C4    ; T # Mn   [4] BENGALI VOWEL SIGN U..BENGALI VOWEL SIGN VOCALIC RR
09CD          ; T # Mn       BENGALI SIGN VIRAMA
09E2..09E3    ; T # Mn   [2] BENGALI VOWEL SIGN VOCALIC L..BENGALI VOWEL SIGN VOCALIC LL
09FE          ; T # Mn       BENGALI SANDHI MARK
0A01..0A02    ; T # Mn   [2] GURMUKHI SIGN ADAK BINDI..GURMUKHI SIGN BINDI
0A3C          ; T # Mn       GURMUKHI SIGN NUKTA
0A41..0A42    ; T # Mn   [2] GURMUKHI VOWEL SIGN U..GURMUKHI VOWEL SIGN UU
0A47..0A48    ; T # Mn   [2] GURMUKHI VOWEL SIGN EE..GURMUKHI VOWEL SIGN AI
0A4B..0A4D    ; T # Mn   [3] GURMUKHI VOWEL SIGN OO..GURMUKHI SIGN VIRAMA
0A51          ; T # Mn       GURMUKHI SIGN UDAAT
0A70..0A71    ; T # Mn   [2] GURMUKHI TIPPI..GURMUKHI ADDAK
0A75          ; T # Mn       GURMUKHI SIGN YAKASH
0A81..0A82    ; T # Mn   [2] GUJARATI SIGN CANDRABINDU..GUJARATI SIGN ANUSVARA
0ABC          ; T # Mn       GUJARATI SIGN NUKTA
0AC1..0AC5    ; T # Mn   [5] GUJARATI VOWEL SIGN U..GUJARATI VOWEL SIGN CANDRA E
0AC7..0AC8    ; T # Mn   [2] GUJARATI VOWEL SIGN E..GUJARATI VOWEL SIGN AI
0ACD          ; T # Mn       GUJARATI SIGN VIRAMA
0AE2..0AE3    ; T # Mn   [2] GUJARATI VOWEL SIGN VOCALIC L..GUJARATI VOWEL SIGN VOCALIC LL
0AFA..0AFF    ; T # Mn   [6] GUJARATI SIGN SUKUN..GUJARATI SIGN TWO-CIRCLE NUKTA ABOVE
0B01          ; T # Mn       ORIYA SIGN CANDRABINDU
0B3C          ; T # Mn       ORIYA SIGN NUKTA
0B3F          ; T # Mn       ORIYA VOWEL SIGN I
0B41..0B44    ; T # Mn   [4] ORIYA VOWEL SIGN U..ORIYA VOWEL SIGN VOCALIC RR
0B4D          ; T # Mn       ORIYA SIGN VIRAMA
0B55..0B56    ; T # Mn   [2] ORIYA SIGN OVERLINE..ORIYA AI LENGTH MARK
0B62..0B63    ; T # Mn   [2] ORIYA VOWEL SIGN VOCALIC L..ORIYA VOWEL SIGN VOCALIC LL
0B82          ; T # Mn       TAMIL SIGN ANUSVARA
0BC0          ; T # Mn       TAMIL VOWEL SIGN II
0BCD          ; T # Mn       TAMIL SIGN VIRAMA
0C00          ; T # Mn       TELUGU SIGN COMBINING CANDRABINDU ABOVE
0C04          ; T # Mn       TELUGU SIGN COMBINING ANUSVARA ABOVE
0C3C          ; T # Mn       TELUGU SIGN NUKTA
0C3E..0C40    ; T # Mn   [3] TELUGU VOWEL SIGN AA..TELUGU VOWEL SIGN II
0C46..0C48    ; T # Mn   [3] TELUGU VOWEL SIGN E..TELUGU VOWEL SIGN AI
0C4A..0C4D    ; T # Mn   [4] TELUGU VOWEL SIGN O..TELUGU SIGN VIRAMA
0C55..0C56    ; T # Mn   [2] TELUGU LENGTH MARK..TELUGU AI LENGTH MARK
0C62..0C63    ; T # Mn   [2] TELUGU VOWEL SIGN VOCALIC L..TELUGU VOWEL SIGN VOCALIC LL
0C81          ; T # Mn       KANNADA SIGN CANDRABINDU
0CBC          ; T # Mn       KANNADA SIGN NUKTA
0CBF          ; T # Mn       KANNADA VOWEL SIGN I
0CC6          ; T # Mn       KANNADA VOWEL SIGN E
0CCC..0CCD    ; T # Mn   [2] KANNADA VOWEL SIGN AU..KANNADA SIGN VIRAMA
0CE2..0CE3    ; T # Mn   [2] KANNADA VOWEL SIGN VOCALIC L..KANNADA VOWEL SIGN VOCALIC LL
0D00..0D01    ; T # Mn   [2] MALAYALAM SIGN COMBINING ANUSVARA ABOVE..MALAYALAM SIGN CANDRABINDU
0D3B..0D3C    ; T # Mn   [2] MALAYALAM SIGN VERTICAL BAR VIRAMA..MALAYALAM SIGN CIRCULAR VIRAMA
0D41..0D44    ; T # Mn   [4] MALAYALAM VOWEL SIGN U..MALAYALAM VOWEL SIGN VOCALIC RR
0D4D          ; T # Mn       MALAYALAM SIGN VIRAMA
0D62..0D63    ; T # Mn   [2] MALAYALAM VOWEL SIGN VOCALIC L..MALAYALAM VOWEL SIGN VOCALIC LL
0D81          ; T # Mn       SINHALA SIGN CANDRABINDU
0DCA          ; T # Mn       SINHALA SIGN AL-LAKUNA
0DD2..0DD4    ; T # Mn   [3] SINHALA VOWEL SIGN KETTI IS-PILLA..SINHALA VOWEL SIGN KETTI PAA-PILLA
0DD6          ; T # Mn       SINHALA VOWEL SIGN DIGA PAA-PILLA
0E31          ; T # Mn       THAI CHARACTER MAI HAN-AKAT
0E34..0E3A    ; T # Mn   [7] THAI CHARACTER SARA I..THAI CHARACTER PHINTHU
0E47..0E4E    ; T # Mn   [8] THAI CHARACTER MAITAIKHU..THAI CHARACTER YAMAKKAN
0EB1          ; T # Mn       LAO VOWEL SIGN MAI KAN
0EB4..0EBC    ; T # Mn   [9] LAO VOWEL SIGN I..LAO SEMIVOWEL SIGN LO
0EC8..0ECE    ; T # Mn   [7] LAO TONE MAI EK..LAO YAMAKKAN
0F18..0F19    ; T # Mn   [2] TIBETAN ASTROLOGICAL SIGN -KHYUD PA..TIBETAN ASTROLOGICAL SIGN SDONG TSHUGS
0F35          ; T # Mn       TIBETAN MARK NGAS BZUNG NYI ZLA
0F37          ; T # Mn       TIBETAN MARK NGAS BZUNG SGOR RTAGS
0F39          ; T # Mn       TIBETAN MARK TSA -PHRU
0F71..0F7E    ; T # Mn  [14] TIBETAN VOWEL SIGN AA..TIBETAN SIGN RJES SU NGA RO
0F80..0F84    ; T # Mn   [5] TIBETAN VOWEL SIGN REVERSED I..TIBETAN MARK HALANTA
0F86..0F87    ; T # Mn   [2] TIBETAN SIGN LCI RTAGS..TIBETAN SIGN YANG RTAGS
0F8D..0F97    ; T # Mn  [11] TIBETAN SUBJOINED SIGN LCE TSA CAN..TIBETAN SUBJOINED LETTER JA
0F99..0FBC    ; T # Mn  [36] TIBETAN SUBJOINED LETTER NYA..TIBETAN SUBJOINED LETTER FIXED-FORM RA
0FC6          ; T # Mn       TIBETAN SYMBOL PADMA GDAN
102D..1030    ; T # Mn   [4] MYANMAR VOWEL SIGN I..MYANMAR VOWEL SIGN UU
1032..1037    ; T # Mn   [6] MYANMAR VOWEL SIGN AI..MYANMAR SIGN DOT BELOW
1039..103A    ; T # Mn   [2] MYANMAR SIGN VIRAMA..MYANMAR SIGN ASAT
103D..103E    ; T # Mn   [2] MYANMAR CONSONANT SIGN MEDIAL WA..MYANMAR CONSONANT SIGN MEDIAL HA
1058..1059    ; T # Mn   [2] MYANMAR VOWEL SIGN VOCALIC L..MYANMAR VOWEL SIGN VOCALIC LL
105E..1060    ; T # Mn   [3] MYANMAR CONSONANT SIGN MON MEDIAL NA..MYANMAR CONSONANT SIGN MON MEDIAL LA
1071..1074    ; T # Mn   [4] MYANMAR VOWEL SIGN GEBA KAREN I..MYANMAR VOWEL SIGN KAYAH EE
1082          ; T # Mn       MYANMAR CONSONANT SIGN SHAN MEDIAL WA
1085..1086    ; T # Mn   [2] MYANMAR VOWEL SIGN SHAN E ABOVE..MYANMAR VOWEL SIGN SHAN FINAL Y
108D          ; T # Mn       MYANMAR SIGN SHAN COUNCIL EMPHATIC TONE
109D          ; T # Mn       MYANMAR VOWEL SIGN AITON AI
135D..135F    ; T # Mn   [3] ETHIOPIC COMBINING GEMINATION AND VOWEL LENGTH MARK..ETHIOPIC COMBINING GEMINATION MARK
1712..1714    ; T # Mn   [3] TAGALOG VOWEL SIGN I..TAGALOG SIGN VIRAMA
1732..1733    ; T # Mn   [2] HANUNOO VOWEL SIGN I..HANUNOO VOWEL SIGN U
1752..1753    ; T # Mn   [2] BUHID VOWEL SIGN I..BUHID VOWEL SIGN U
1772..1773    ; T # Mn   [2] TAGBANWA VOWEL SIGN I..TAGBANWA VOWEL SIGN U
17B4..17B5    ; T # Mn   [2] KHMER VOWEL INHERENT AQ..KHMER VOWEL INHERENT AA
17B7..17BD    ; T # Mn   [7] KHMER VOWEL SIGN I..KHMER VOWEL SIGN UA
17C6          ; T # Mn       KHMER SIGN NIKAHIT
17C9..17D3    ; T # Mn  [11] KHMER SIGN MUUSIKATOAN..KHMER SIGN BATHAMASAT
17DD          ; T # Mn       KHMER SIGN ATTHACAN
180B..180D    ; T # Mn   [3] MONGOLIAN FREE VARIATION SELECTOR ONE..MONGOLIAN FREE VARIATION SELECTOR THREE
180F          ; T # Mn       MONGOLIAN FREE VARIATION SELECTOR FOUR
1885..1886    ; T # Mn   [2] MONGOLIAN LETTER ALI GALI BALUDA..MONGOLIAN LETTER ALI GALI THREE BALUDA
18A9          ; T # Mn       MONGOLIAN LETTER ALI GALI DAGALGA
1920..1922    ; T # Mn   [3] LIMBU VOWEL SIGN A..LIMBU VOWEL SIGN U
1927..1928    ; T # Mn   [2] LIMBU VOWEL SIGN E..LIMBU VOWEL SIGN O
1932          ; T # Mn       LIMBU SMALL LETTER ANUSVARA
1939..193B    ; T # Mn   [3] LIMBU SIGN MUKPHRENG..LIMBU SIGN SA-I
1A17..1A18    ; T # Mn   [2] BUGINESE VOWEL SIGN I..BUGINESE VOWEL SIGN U
1A1B          ; T # Mn       BUGINESE VOWEL SIGN AE
1A56          ; T # Mn       TAI THAM CONSONANT SIGN MEDIAL LA
1A58..1A5E    ; T # Mn   [7] TAI THAM SIGN MAI KANG LAI..TAI THAM CONSONANT SIGN SA
1A60          ; T # Mn       TAI THAM SIGN SAKOT
1A62          ; T # Mn       TAI THAM VOWEL SIGN MAI SAT
1A65..1A6C    ; T # Mn   [8] TAI THAM VOWEL SIGN I..TAI THAM VOWEL SIGN OA BELOW
1A73..1A7C    ; T # Mn  [10] TAI THAM VOWEL SIGN OA ABOVE..TAI THAM SIGN KHUEN-LUE KARAN
1A7F          ; T # Mn       TAI THAM COMBINING CRYPTOGRAMMIC DOT
1AB0..1ABD    ; T # Mn  [14] COMBINING DOUBLED CIRCUMFLEX ACCENT..COMBINING PARENTHESES BELOW
1ABE          ; T # Me       COMBINING PARENTHESES OVERLAY
1ABF..1ACE    ; T # Mn  [16] COMBINING LATIN SMALL LETTER W BELOW..COMBINING LATIN SMALL LETTER INSULAR T
1B00..1B03    ; T # Mn   [4] BALINESE SIGN ULU RICEM..BALINESE SIGN SURANG
1B34          ; T # Mn       BALINESE SIGN REREKAN
1B36..1B3A    ; T # Mn   [5] BALINESE VOWEL SIGN ULU..BALINESE VOWEL SIGN RA REPA
1B3C          ; T # Mn       BALINESE VOWEL SIGN LA LENGA
1B42          ; T # Mn       BALINESE VOWEL SIGN PEPET
1B6B..1B73    ; T # Mn   [9] BALINESE MUSICAL SYMBOL COMBINING TEGEH..BALINESE MUSICAL SYMBOL COMBINING GONG
1B80..1B81    ; T # Mn   [2] SUNDANESE SIGN PANYECEK..SUNDANESE SIGN PANGLAYAR
1BA2..1BA5    ; T # Mn   [4] SUNDANESE CONSONANT SIGN PANYAKRA..SUNDANESE VOWEL SIGN PANYUKU
1BA8..1BA9    ; T # Mn   [2] SUNDANESE VOWEL SIGN PAMEPET..SUNDANESE VOWEL SIGN PANEULEUNG
1BAB..1BAD    ; T # Mn   [3] SUNDANESE SIGN VIRAMA..SUNDANESE CONSONANT SIGN PASANGAN WA
1BE6          ; T # Mn       BATAK SIGN TOMPI
1BE8..1BE9    ; T # Mn   [2] BATAK VOWEL SIGN PAKPAK E..BATAK VOWEL SIGN EE
1BED          ; T # Mn       BATAK VOWEL SIGN KARO O
1BEF..1BF1    ; T # Mn   [3] BATAK VOWEL SIGN U FOR SIMALUNGUN SA..BATAK CONSONANT SIGN H
1C2C..1C33    ; T # Mn   [8] LEPCHA VOWEL SIGN E..LEPCHA CONSONANT SIGN T
1C36..1C37    ; T # Mn   [2] LEPCHA SIGN RAN..LEPCHA SIGN NUKTA
1CD0..1CD2    ; T # Mn   [3] VEDIC TONE KARSHANA..VEDIC TONE PRENKHA
1CD4..1CE0    ; T # Mn  [13] VEDIC SIGN YAJURVEDIC MIDLINE SVARITA..VEDIC TONE RIGVEDIC KASHMIRI INDEPENDENT SVARITA
1CE2..1CE8    ; T # Mn   [7] VEDIC SIGN VISARGA SVARITA..VEDIC SIGN VISARGA ANUDATTA WITH TAIL
1CED          ; T # Mn       VEDIC SIGN TIRYAK
1CF4          ; T # Mn       VEDIC TONE CANDRA ABOVE
1CF8..1CF9    ; T # Mn   [2] VEDIC TONE RING ABOVE..VEDIC TONE DOUBLE RING ABOVE
1DC0..1DFF    ; T # Mn  [64] COMBINING DOTTED GRAVE ACCENT..COMBINING RIGHT ARROWHEAD AND DOWN ARROWHEAD BELOW
200B          ; T # Cf       ZERO WIDTH SPACE
200E..200F    ; T # Cf   [2] LEFT-TO-RIGHT MARK..RIGHT-TO-LEFT MARK
202A..202E    ; T # Cf   [5] LEFT-TO-RIGHT EMBEDDING..RIGHT-TO-LEFT OVERRIDE
2060..2064    ; T # Cf   [5] WORD JOINER..INVISIBLE PLUS
206A..206F    ; T # Cf   [6] INHIBIT SYMMETRIC SWAPPING..NOMINAL DIGIT SHAPES
20D0..20DC    ; T # Mn  [13] COMBINING LEFT HARPOON ABOVE..COMBINING FOUR DOTS ABOVE
20DD..20E0    ; T # Me   [4] COMBINING ENCLOSING CIRCLE..COMBINING ENCLOSING CIRCLE BACKSLASH
20E1          ; T # Mn       COMBINING LEFT RIGHT ARROW ABOVE
20E2..20E4    ; T # Me   [3] COMBINING ENCLOSING SCREEN..COMBINING ENCLOSING UPWARD POINTING TRIANGLE
20E5..20F0    ; T # Mn  [12] COMBINING REVERSE SOLIDUS OVERLAY..COMBINING ASTERISK ABOVE
2CEF..2CF1    ; T # Mn   [3] COPTIC COMBINING NI ABOVE..COPTIC COMBINING SPIRITUS LENIS
2D7F          ; T # Mn       TIFINAGH CONSONANT JOINER
2DE0..2DFF    ; T # Mn  [32] COMBINING CYRILLIC LETTER BE..COMBINING CYRILLIC LETTER IOTIFIED BIG YUS
302A..302D    ; T # Mn   [4] IDEOGRAPHIC LEVEL TONE MARK..IDEOGRAPHIC ENTERING TONE MARK
3099..309A    ; T # Mn   [2] COMBINING KATAKANA-HIRAGANA VOICED SOUND MARK..COMBINING KATAKANA-HIRAGANA SEMI-VOICED SOUND MARK
A66F          ; T # Mn       COMBINING CYRILLIC VZMET
A670..A672    ; T # Me   [3] COMBINING CYRILLIC TEN MILLIONS SIGN..COMBINING CYRILLIC THOUSAND MILLIONS SIGN
A674..A67D    ; T # Mn  [10] COMBINING CYRILLIC LETTER UKRAINIAN IE..COMBINING CYRILLIC PAYEROK
A69E..A69F    ; T # Mn   [2] COMBINING CYRILLIC LETTER EF..COMBINING CYRILLIC LETTER IOTIFIED E
A6F0..A6F1    ; T # Mn   [2] BAMUM COMBINING MARK KOQNDON..BAMUM COMBINING MARK TUKWENTIS
A802          ; T # Mn       SYLOTI NAGRI SIGN DVISVARA
A806          ; T # Mn       SYLOTI NAGRI SIGN HASANTA
A80B          ; T # Mn       SYLOTI NAGRI SIGN ANUSVARA
A825..A826    ; T # Mn   [2] SYLOTI NAGRI VOWEL SIGN U..SYLOTI NAGRI VOWEL SIGN E
A82C          ; T # Mn       SYLOTI NAGRI SIGN ALTERNATE HASANTA
A8C4..A8C5    ; T # Mn   [2] SAURASHTRA SIGN VIRAMA..SAURASHTRA SIGN CANDRABINDU
A8E0..A8F1    ; T # Mn  [18] COMBINING DEVANAGARI DIGIT ZERO..COMBINING DEVANAGARI SIGN AVAGRAHA
A8FF          ; T # Mn       DEVANAGARI VOWEL SIGN AY
A926..A92D    ; T # Mn   [8] KAYAH LI VOWEL UE..KAYAH LI TONE CALYA PLOPHU
A947..A951    ; T # Mn  [11] REJANG VOWEL SIGN I..REJANG CONSONANT SIGN R
A980..A982    ; T # Mn   [3] JAVANESE SIGN PANYANGGA..JAVANESE SIGN LAYAR
A9B3          ; T # Mn       JAVANESE SIGN CECAK TELU
A9B6..A9B9    ; T # Mn   [4] JAVANESE VOWEL SIGN WULU..JAVANESE VOWEL SIGN SUKU MENDUT
A9BC..A9BD    ; T # Mn   [2] JAVANESE VOWEL SIGN PEPET..JAVANESE CONSONANT SIGN KERET
A9E5          ; T # Mn       MYANMAR SIGN SHAN SAW
AA29..AA2E    ; T # Mn   [6] CHAM VOWEL SIGN AA..CHAM VOWEL SIGN OE
AA31..AA32    ; T # Mn   [2] CHAM VOWEL SIGN AU..CHAM VOWEL SIGN UE
AA35..AA36    ; T # Mn   [2] CHAM CONSONANT SIGN LA..CHAM CONSONANT SIGN WA
AA43          ; T # Mn       CHAM CONSONANT SIGN FINAL NG
AA4C          ; T # Mn       CHAM CONSONANT SIGN FINAL M
AA7C          ; T # Mn       MYANMAR SIGN TAI LAING TONE-2
AAB0          ; T # Mn       TAI VIET MAI KANG
AAB2..AAB4    ; T # Mn   [3] TAI VIET VOWEL I..TAI VIET VOWEL U
AAB7..AAB8    ; T # Mn   [2] TAI VIET MAI KHIT..TAI VIET VOWEL IA
AABE..AABF    ; T # Mn   [2] TAI VIET VOWEL AM..TAI VIET TONE MAI EK
AAC1          ; T # Mn       TAI VIET TONE MAI THO
AAEC..AAED    ; T # Mn   [2] MEETEI MAYEK VOWEL SIGN UU..MEETEI MAYEK VOWEL SIGN AAI
AAF6          ; T # Mn       MEETEI MAYEK VIRAMA
ABE5          ; T # Mn       MEETEI MAYEK VOWEL SIGN ANAP
ABE8          ; T # Mn       MEETEI MAYEK VOWEL SIGN UNAP
ABED          ; T # Mn       MEETEI MAYEK APUN IYEK
FB1E          ; T # Mn       HEBREW POINT JUDEO-SPANISH VARIKA
FE00..FE0F    ; T # Mn  [16] VARIATION SELECTOR-1..VARIATION SELECTOR-16
FE20..FE2F    ; T # Mn  [16] COMBINING LIGATURE LEFT HALF..COMBINING CYRILLIC TITLO RIGHT HALF
FEFF          ; T # Cf       ZERO WIDTH NO-BREAK SPACE
FFF9..FFFB    ; T # Cf   [3] INTERLINEAR ANNOTATION ANCHOR..INTERLINEAR ANNOTATION TERMINATOR
101FD         ; T # Mn       PHAISTOS DISC SIGN COMBINING OBLIQUE STROKE
102E0         ; T # Mn       COPTIC EPACT THOUSANDS MARK
10376..1037A  ; T # Mn   [5] COMBINING OLD PERMIC LETTER AN..COMBINING OLD PERMIC LETTER SII
10A01..10A03  ; T # Mn   [3] KHAROSHTHI VOWEL SIGN I..KHAROSHTHI VOWEL SIGN VOCALIC R
10A05..10A06  ; T # Mn   [2] KHAROSHTHI VOWEL SIGN E..KHAROSHTHI VOWEL SIGN O
10A0C..10A0F  ; T # Mn   [4] KHAROSHTHI VOWEL LENGTH MARK..KHAROSHTHI SIGN VISARGA
10A38..10A3A  ; T # Mn   [3] KHAROSHTHI SIGN BAR ABOVE..KHAROSHTHI SIGN DOT BELOW
10A3F         ; T # Mn       KHAROSHTHI VIRAMA
10AE5..10AE6  ; T # Mn   [2] MANICHAEAN ABBREVIATION MARK ABOVE..MANICHAEAN ABBREVIATION MARK BELOW
10D24..10D27  ; T # Mn   [4] HANIFI ROHINGYA SIGN HARBAHAY..HANIFI ROHINGYA SIGN TASSI
10D69..10D6D  ; T # Mn   [5] GARAY VOWEL SIGN E..GARAY CONSONANT NASALIZATION MARK
10EAB..10EAC  ; T # Mn   [2] YEZIDI COMBINING HAMZA MARK..YEZIDI COMBINING MADDA MARK
10EFC..10EFF  ; T # Mn   [4] ARABIC COMBINING ALEF OVERLAY..ARABIC SMALL LOW WORD MADDA
10F46..10F50  ; T # Mn  [11] SOGDIAN COMBINING DOT BELOW..SOGDIAN COMBINING STROKE BELOW
10F82..10F85  ; T # Mn   [4] OLD UYGHUR COMBINING DOT ABOVE..OLD UYGHUR COMBINING TWO DOTS BELOW
11001         ; T # Mn       BRAHMI SIGN ANUSVARA
11038..11046  ; T # Mn  [15] BRAHMI VOWEL SIGN AA..BRAHMI VIRAMA
11070         ; T # Mn       BRAHMI SIGN OLD TAMIL VIRAMA
11073..11074  ; T # Mn   [2] BRAHMI VOWEL SIGN OLD TAMIL SHORT E..BRAHMI VOWEL SIGN OLD TAMIL SHORT O
1107F..11081  ; T # Mn   [3] BRAHMI NUMBER JOINER..KAITHI SIGN ANUSVARA
110B3..110B6  ; T # Mn   [4] KAITHI VOWEL SIGN U..KAITHI VOWEL SIGN AI
110B9..110BA  ; T # Mn   [2] KAITHI SIGN VIRAMA..KAITHI SIGN NUKTA
110C2         ; T # Mn       KAITHI VOWEL SIGN VOCALIC R
11100..11102  ; T # Mn   [3] CHAKMA SIGN CANDRABINDU..CHAKMA SIGN VISARGA
11127..1112B  ; T # Mn   [5] CHAKMA VOWEL SIGN A..CHAKMA VOWEL SIGN UU
1112D..11134  ; T # Mn   [8] CHAKMA VOWEL SIGN AI..CHAKMA MAAYYAA
11173         ; T # Mn       MAHAJANI SIGN NUKTA
11180..11181  ; T # Mn   [2] SHARADA SIGN CANDRABINDU..SHARADA SIGN ANUSVARA
111B6..111BE  ; T # Mn   [9] SHARADA VOWEL SIGN U..SHARADA VOWEL SIGN O
111C9..111CC  ; T # Mn   [4] SHARADA SANDHI MARK..SHARADA EXTRA SHORT VOWEL MARK
111CF         ; T # Mn       SHARADA SIGN INVERTED CANDRABINDU
1122F..11231  ; T # Mn   [3] KHOJKI VOWEL SIGN U..KHOJKI VOWEL SIGN AI
11234         ; T # Mn       KHOJKI SIGN ANUSVARA
11236..11237  ; T # Mn   [2] KHOJKI SIGN NUKTA..KHOJKI SIGN SHADDA
1123E         ; T # Mn       KHOJKI SIGN SUKUN
11241         ; T # Mn       KHOJKI VOWEL SIGN VOCALIC R
112DF         ; T # Mn       KHUDAWADI SIGN ANUSVARA
112E3..112EA  ; T # Mn   [8] KHUDAWADI VOWEL SIGN U..KHUDAWADI SIGN VIRAMA
11300..11301  ; T # Mn   [2] GRANTHA SIGN COMBINING ANUSVARA ABOVE..GRANTHA SIGN CANDRABINDU
1133B..1133C  ; T # Mn   [2] COMBINING BINDU BELOW..GRANTHA SIGN NUKTA
11340         ; T # Mn       GRANTHA VOWEL SIGN II
11366..1136C  ; T # Mn   [7] COMBINING GRANTHA DIGIT ZERO..COMBINING GRANTHA DIGIT SIX
11370..11374  ; T # Mn   [5] COMBINING GRANTHA LETTER A..COMBINING GRANTHA LETTER PA
113BB..113C0  ; T # Mn   [6] TULU-TIGALARI VOWEL SIGN U..TULU-TIGALARI VOWEL SIGN VOCALIC LL
113CE         ; T # Mn       TULU-TIGALARI SIGN VIRAMA
113D0         ; T # Mn       TULU-TIGALARI CONJOINER
113D2         ; T # Mn       TULU-TIGALARI GEMINATION MARK
113E1..113E2  ; T # Mn   [2] TULU-TIGALARI VEDIC TONE SVARITA..TULU-TIGALARI VEDIC TONE ANUDATTA
11438..1143F  ; T # Mn   [8] NEWA VOWEL SIGN U..NEWA VOWEL SIGN AI
11442..11444  ; T # Mn   [3] NEWA SIGN VIRAMA..NEWA SIGN ANUSVARA
11446         ; T # Mn       NEWA SIGN NUKTA
1145E         ; T # Mn       NEWA SANDHI MARK
114B3..114B8  ; T # Mn   [6] TIRHUTA VOWEL SIGN U..TIRHUTA VOWEL SIGN VOCALIC LL
114BA         ; T # Mn       TIRHUTA VOWEL SIGN SHORT E
114BF..114C0  ; T # Mn   [2] TIRHUTA SIGN CANDRABINDU..TIRHUTA SIGN ANUSVARA
114C2..114C3  ; T # Mn   [2] TIRHUTA SIGN VIRAMA..TIRHUTA SIGN NUKTA
115B2..115B5  ; T # Mn   [4] SIDDHAM VOWEL SIGN U..SIDDHAM VOWEL SIGN VOCALIC RR
115BC..115BD  ; T # Mn   [2] SIDDHAM SIGN CANDRABINDU..SIDDHAM SIGN ANUSVARA
115BF..115C0  ; T # Mn   [2] SIDDHAM SIGN VIRAMA..SIDDHAM SIGN NUKTA
115DC..115DD  ; T # Mn   [2] SIDDHAM VOWEL SIGN ALTERNATE U..SIDDHAM VOWEL SIGN ALTERNATE UU
11633..1163A  ; T # Mn   [8] MODI VOWEL SIGN U..MODI VOWEL SIGN AI
1163D         ; T # Mn       MODI SIGN ANUSVARA
1163F..11640  ; T # Mn   [2] MODI SIGN VIRAMA..MODI SIGN ARDHACANDRA
116AB         ; T # Mn       TAKRI SIGN ANUSVARA
116AD         ; T # Mn       TAKRI VOWEL SIGN AA
116B0..116B5  ; T # Mn   [6] TAKRI VOWEL SIGN U..TAKRI VOWEL SIGN AU
116B7         ; T # Mn       TAKRI SIGN NUKTA
1171D         ; T # Mn       AHOM CONSONANT SIGN MEDIAL LA
1171F         ; T # Mn       AHOM CONSONANT SIGN MEDIAL LIGATING RA
11722..11725  ; T # Mn   [4] AHOM VOWEL SIGN I..AHOM VOWEL SIGN UU
11727..1172B  ; T # Mn   [5] AHOM VOWEL SIGN AW..AHOM SIGN KILLER
1182F..11837  ; T # Mn   [9] DOGRA VOWEL SIGN U..DOGRA SIGN ANUSVARA
11839..1183A  ; T # Mn   [2] DOGRA SIGN VIRAMA..DOGRA SIGN NUKTA
1193B..1193C  ; T # Mn   [2] DIVES AKURU SIGN ANUSVARA..DIVES AKURU SIGN CANDRABINDU
1193E         ; T # Mn       DIVES AKURU VIRAMA
11943         ; T # Mn       DIVES AKURU SIGN NUKTA
119D4..119D7  ; T # Mn   [4] NANDINAGARI VOWEL SIGN U..NANDINAGARI VOWEL SIGN VOCALIC RR
119DA..119DB  ; T # Mn   [2] NANDINAGARI VOWEL SIGN E..NANDINAGARI VOWEL SIGN AI
119E0         ; T # Mn       NANDINAGARI SIGN VIRAMA
11A01..11A0A  ; T # Mn  [10] ZANABAZAR SQUARE VOWEL SIGN I..ZANABAZAR SQUARE VOWEL LENGTH MARK
11A33..11A38  ; T # Mn   [6] ZANABAZAR SQUARE FINAL CONSONANT MARK..ZANABAZAR SQUARE SIGN ANUSVARA
11A3B..11A3E  ; T # Mn   [4] ZANABAZAR SQUARE CLUSTER-FINAL LETTER YA..ZANABAZAR SQUARE CLUSTER-FINAL LETTER VA
11A47         ; T # Mn       ZANABAZAR SQUARE SUBJOINER
11A51..11A56  ; T # Mn   [6] SOYOMBO VOWEL SIGN I..SOYOMBO VOWEL SIGN OE
11A59..11A5B  ; T # Mn   [3] SOYOMBO VOWEL SIGN VOCALIC R..SOYOMBO VOWEL LENGTH MARK
11A8A..11A96  ; T # Mn  [13] SOYOMBO FINAL CONSONANT SIGN G..SOYOMBO SIGN ANUSVARA
11A98..11A99  ; T # Mn   [2] SOYOMBO GEMINATION MARK..SOYOMBO SUBJOINER
11C30..11C36  ; T # Mn   [7] BHAIKSUKI VOWEL SIGN I..BHAIKSUKI VOWEL SIGN VOCALIC L
11C38..11C3D  ; T # Mn   [6] BHAIKSUKI VOWEL SIGN E..BHAIKSUKI SIGN ANUSVARA
11C3F         ; T # Mn       BHAIKSUKI SIGN VIRAMA
11C92..11CA7  ; T # Mn  [22] MARCHEN SUBJOINED LETTER KA..MARCHEN SUBJOINED LETTER ZA
11CAA..11CB0  ; T # Mn   [7] MARCHEN SUBJOINED LETTER RA..MARCHEN VOWEL SIGN AA
11CB2..11CB3  ; T # Mn   [2] MARCHEN VOWEL SIGN U..MARCHEN VOWEL SIGN E
11CB5..11CB6  ; T # Mn   [2] MARCHEN SIGN ANUSVARA..MARCHEN SIGN CANDRABINDU
11D31..11D36  ; T # Mn   [6] MASARAM GONDI VOWEL SIGN AA..MASARAM GONDI VOWEL SIGN VOCALIC R
11D3A         ; T # Mn       MASARAM GONDI VOWEL SIGN E
11D3C..11D3D  ; T # Mn   [2] MASARAM GONDI VOWEL SIGN AI..MASARAM GONDI VOWEL SIGN O
11D3F..11D45  ; T # Mn   [7] MASARAM GONDI VOWEL SIGN AU..MASARAM GONDI VIRAMA
11D47         ; T # Mn       MASARAM GONDI RA-KARA
11D90..11D91  ; T # Mn   [2] GUNJALA GONDI VOWEL SIGN EE..GUNJALA GONDI VOWEL SIGN AI
11D95         ; T # Mn       GUNJALA GONDI SIGN ANUSVARA
11D97         ; T # Mn       GUNJALA GONDI VIRAMA
11EF3..11EF4  ; T # Mn   [2] MAKASAR VOWEL SIGN I..MAKASAR VOWEL SIGN U
11F00..11F01  ; T # Mn   [2] KAWI SIGN CANDRABINDU..KAWI SIGN ANUSVARA
11F36..11F3A  ; T # Mn   [5] KAWI VOWEL SIGN I..KAWI VOWEL SIGN VOCALIC R
11F40         ; T # Mn       KAWI VOWEL SIGN EU
11F42         ; T # Mn       KAWI CONJOINER
11F5A         ; T # Mn       KAWI SIGN NUKTA
13430..1343F  ; T # Cf  [16] EGYPTIAN HIEROGLYPH VERTICAL JOINER..EGYPTIAN HIEROGLYPH END WALLED ENCLOSURE
13440         ; T # Mn       EGYPTIAN HIEROGLYPH MIRROR HORIZONTALLY
13447..13455  ; T # Mn  [15] EGYPTIAN HIEROGLYPH MODIFIER DAMAGED AT TOP START..EGYPTIAN HIEROGLYPH MODIFIER DAMAGED
1611E..16129  ; T # Mn  [12] GURUNG KHEMA VOWEL SIGN AA..GURUNG KHEMA VOWEL LENGTH MARK
1612D..1612F  ; T # Mn   [3] GURUNG KHEMA SIGN ANUSVARA..GURUNG KHEMA SIGN THOLHOMA
16AF0..16AF4  ; T # Mn   [5] BASSA VAH COMBINING HIGH TONE..BASSA VAH COMBINING HIGH-LOW TONE
16B30..16B36  ; T # Mn   [7] PAHAWH HMONG MARK CIM TUB..PAHAWH HMONG MARK CIM TAUM
16F4F         ; T # Mn       MIAO SIGN CONSONANT MODIFIER BAR
16F8F..16F92  ; T # Mn   [4] MIAO TONE RIGHT..MIAO TONE BELOW
16FE4         ; T # Mn       KHITAN SMALL SCRIPT FILLER
1BC9D..1BC9E  ; T # Mn   [2] DUPLOYAN THICK LETTER SELECTOR..DUPLOYAN DOUBLE MARK
1BCA0..1BCA3  ; T # Cf   [4] SHORTHAND FORMAT LETTER OVERLAP..SHORTHAND FORMAT UP STEP
1CF00..1CF2D  ; T # Mn  [46] ZNAMENNY COMBINING MARK GORAZDO NIZKO S KRYZHEM ON LEFT..ZNAMENNY COMBINING MARK KRYZH ON LEFT
1CF30..1CF46  ; T # Mn  [23] ZNAMENNY COMBINING TONAL RANGE MARK MRACHNO..ZNAMENNY PRIZNAK MODIFIER ROG
1D167..1D169  ; T # Mn   [3] MUSICAL SYMBOL COMBINING TREMOLO-1..MUSICAL SYMBOL COMBINING TREMOLO-3
1D173..1D17A  ; T # Cf   [8] MUSICAL SYMBOL BEGIN BEAM..MUSICAL SYMBOL END PHRASE
1D17B..1D182  ; T # Mn   [8] MUSICAL SYMBOL COMBINING ACCENT..MUSICAL SYMBOL COMBINING LOURE
1D185..1D18B  ; T # Mn   [7] MUSICAL SYMBOL COMBINING DOIT..MUSICAL SYMBOL COMBINING TRIPLE TONGUE
1D1AA..1D1AD  ; T # Mn   [4] MUSICAL SYMBOL COMBINING DOWN BOW..MUSICAL SYMBOL COMBINING SNAP PIZZICATO
1D242..1D244  ; T # Mn   [3] COMBINING GREEK MUSICAL TRISEME..COMBINING GREEK MUSICAL PENTASEME
1DA00..1DA36  ; T # Mn  [55] SIGNWRITING HEAD RIM..SIGNWRITING AIR SUCKING IN
1DA3B..1DA6C  ; T # Mn  [50] SIGNWRITING MOUTH CLOSED NEUTRAL..SIGNWRITING EXCITEMENT
1DA75         ; T # Mn       SIGNWRITING UPPER BODY TILTING FROM HIP JOINTS
1DA84         ; T # Mn       SIGNWRITING LOCATION HEAD NECK
1DA9B..1DA9F  ; T # Mn   [5] SIGNWRITING FILL MODIFIER-2..SIGNWRITING FILL MODIFIER-6
1DAA1..1DAAF  ; T # Mn  [15] SIGNWRITING ROTATION MODIFIER-2..SIGNWRITING ROTATION MODIFIER-16
1E000..1E006  ; T # Mn   [7] COMBINING GLAGOLITIC LETTER AZU..COMBINING GLAGOLITIC LETTER ZHIVETE
1E008..1E018  ; T # Mn  [17] COMBINING GLAGOLITIC LETTER ZEMLJA..COMBINING GLAGOLITIC LETTER HERU
1E01B..1E021  ; T # Mn   [7] COMBINING GLAGOLITIC LETTER SHTA..COMBINING GLAGOLITIC LETTER YATI
1E023..1E024  ; T # Mn   [2] COMBINING GLAGOLITIC LETTER YU..COMBINING GLAGOLITIC LETTER SMALL YUS
1E026..1E02A  ; T # Mn   [5] COMBINING GLAGOLITIC LETTER YO..COMBINING GLAGOLITIC LETTER FITA
1E08F         ; T # Mn       COMBINING CYRILLIC SMALL LETTER BYELORUSSIAN-UKRAINIAN I
1E130..1E136  ; T # Mn   [7] NYIAKENG PUACHUE HMONG TONE-B..NYIAKENG PUACHUE HMONG TONE-D
1E2AE         ; T # Mn       TOTO SIGN RISING TONE
1E2EC..1E2EF  ; T # Mn   [4] WANCHO TONE TUP..WANCHO TONE KOINI
1E4EC..1E4EF  ; T # Mn   [4] NAG MUNDARI SIGN MUHOR..NAG MUNDARI SIGN SUTUH
1E5EE..1E5EF  ; T # Mn   [2] OL ONAL SIGN MU..OL ONAL SIGN IKIR
1E8D0..1E8D6  ; T # Mn   [7] MENDE KIKAKUI COMBINING NUMBER TEENS..MENDE KIKAKUI COMBINING NUMBER MILLIONS
1E944..1E94A  ; T # Mn   [7] ADLAM ALIF LENGTHENER..ADLAM NUKTA
1E94B         ; T # Lm       ADLAM NASALIZATION MARK
E0001         ; T # Cf       LANGUAGE TAG
E0020..E007F  ; T # Cf  [96] TAG SPACE..CANCEL TAG
E0100..E01EF  ; T # Mn [240] VARIATION SELECTOR-17..VARIATION SELECTOR-256

# Total code points: 2185

# EOF
`
let joiningType = {};
function ArabicShapingParse(){
    shaping = shaping.replace(/^#.*\n?/gm, "")
    shaping = shaping.replace(/^\s*\n?/gm, "")

    let lines = shaping.split("\n")
    for(let line of lines){
        const l = line.split("; ");
        if(l.length > 1){
            joiningType[String.fromCodePoint(parseInt(l[0], 16))] = l[2];
        }
    }

    derived_shaping = derived_shaping.replace(/^#.*\n?/gm, "")
    derived_shaping = derived_shaping.replace(/ #.*/gm, "")
    derived_shaping = derived_shaping.replace(/^\s*\n?/gm, "")
    derived_shaping = derived_shaping.replace(/\s+; /gm, ";")
    lines = derived_shaping.split("\n");
    for(let line of lines){
        const l = line.split(";");
        if(l.length < 2) continue;
        if(l[0].includes("..")){
            let edges = l[0].split("..");
            edges[0] = parseInt(edges[0], 16);
            edges[1] = parseInt(edges[1], 16);
            let i = edges[0];
            while(i <= edges[1]){
                joiningType[String.fromCodePoint(i)] = l[1];
                i++;
            }
        }
        else{
            joiningType[String.fromCodePoint(parseInt(l[0], 16))] = l[1];
        }
    }
}
